import Link from "next/link";
import { chatGPTSignInPath, getChatGPTUser } from "../chatgpt-auth";

export const dynamic = "force-dynamic";

export default async function SignInPage() {
  const user = await getChatGPTUser();
  if (user) return <main className="signin-page"><section className="signin-card"><span className="badge badge-green">SIGNED IN</span><h1>Welcome back, {user.displayName}</h1><p>Your rehearsal history, preferences, and imported repository snapshots are saved to this account.</p><div className="signin-actions"><Link className="button button-dark" href="/dashboard">Open dashboard →</Link><Link className="button button-ghost" href="/repositories">Choose a repository</Link></div></section></main>;
  return <main className="signin-page"><div className="signin-layout"><aside className="signin-context"><p className="eyebrow">YOUR READINESS RECORD</p><h2>Keep the evidence of how you investigate.</h2><p>Scores are more useful when they form a pattern. An account turns individual rehearsals into a durable view of diagnosis, evidence, repair, verification, and prevention.</p><div className="signin-signal"><span><small>DIAGNOSIS</small><i style={{ width: "88%" }} /></span><span><small>EVIDENCE</small><i style={{ width: "76%" }} /></span><span><small>VERIFICATION</small><i style={{ width: "82%" }} /></span></div><small>Illustrative readiness profile</small></aside><section className="signin-card"><p className="eyebrow">OPTIONAL ACCOUNT</p><h1>Save your rehearsal progress</h1><p>Public cases, GitHub imports, and local uploads work without an account. Sign in when you want history, preferences, and safe repository snapshots to follow you.</p><Link className="provider-button" href={chatGPTSignInPath("/dashboard")}><span className="provider-mark">OA</span><span><b>Continue with ChatGPT</b><small>Secure sign-in is handled by OpenAI</small></span><strong>→</strong></Link><div className="signin-divider"><span>ACCOUNT BOUNDARY</span></div><ul className="signin-benefits"><li>Save verified scores and completed rehearsals</li><li>Remember practice-mode and time-limit defaults</li><li>Reuse filtered GitHub and local source snapshots</li><li>Passwords, excluded secrets, and originals are never stored</li></ul><Link className="text-link" href="/repositories">Continue without an account →</Link></section></div></main>;
}
