import { ensureAccount, ensureAccountSchema } from "../accounts/account-service";
import { saveAccountRehearsal } from "../accounts/account-service";
import { getRepository, loadRepositoryFiles, type RepositoryUser } from "../repositories/repository-service";
import { isSafeArchiveEntry } from "../security/path-validation";
import { accessToken, repositoryBucket, runtimeDatabase, sha256 } from "../storage/runtime";
import { scenarioFor } from "./scenarios";
import type { RehearsalReport, RehearsalSession, RehearsalStatus, TimelineEvent, WorkspaceFile } from "./types";
import type { AccountMode } from "../accounts/types";
import type { ValidationResult } from "../types";
import { enhanceReport } from "../ai/report-enhancer";
import { applyGeneratedIncident, evaluateGeneratedIncident, generateIncidentBlueprint, GENERATED_INCIDENT_ID, hasGeneratedWorkspaceEdits, preventionForGeneratedIncident, type GeneratedIncidentBlueprint } from "../incidents/brain";
import type { IncidentTemplate } from "../types";
import { DAILY_REPOSITORY_ID, dailyChallenge } from "./daily";
import { recordDailyLeaderboardResult } from "./daily-leaderboard";
import { normalizeSubmissionScore } from "./submission-score";
import { trackRehearsalFunnel } from "../analytics/rehearsal-analytics";
import { customIncidentBlueprint } from "../incidents/custom-incidents";

type SessionRow = { id:string;owner_account_id:string|null;access_token_hash:string;repository_id:string;repository_name:string;incident_template_id:string;difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED";mode:AccountMode;time_limit_minutes:number;status:RehearsalStatus;hint_count:number;hypotheses_json:string;timeline_json:string;workspace_key:string|null;score:number|null;validation_json:string|null;report_json:string|null;created_at:string;started_at:string|null;completed_at:string|null;expires_at:string };
type WorkspaceEnvelope = { version: 2; files: WorkspaceFile[]; generatedIncident?: GeneratedIncidentBlueprint };
export type SessionUser=RepositoryUser;

export async function ensureRehearsalSchema(){await ensureAccountSchema();const db=runtimeDatabase();await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS rehearsal_sessions (
    id TEXT PRIMARY KEY NOT NULL, owner_account_id TEXT, access_token_hash TEXT NOT NULL, repository_id TEXT NOT NULL,
    repository_name TEXT NOT NULL, incident_template_id TEXT NOT NULL, difficulty TEXT NOT NULL, mode TEXT NOT NULL,
    time_limit_minutes INTEGER NOT NULL, status TEXT NOT NULL, hint_count INTEGER NOT NULL DEFAULT 0,
    hypotheses_json TEXT NOT NULL DEFAULT '[]', timeline_json TEXT NOT NULL DEFAULT '[]', workspace_key TEXT,
    score INTEGER, validation_json TEXT, report_json TEXT, created_at TEXT NOT NULL, started_at TEXT, completed_at TEXT,
    expires_at TEXT NOT NULL, FOREIGN KEY (owner_account_id) REFERENCES accounts(id) ON DELETE CASCADE
  )`),
  db.prepare("CREATE INDEX IF NOT EXISTS rehearsal_sessions_owner_date_idx ON rehearsal_sessions(owner_account_id, created_at DESC)"),
  db.prepare("CREATE INDEX IF NOT EXISTS rehearsal_sessions_expiry_idx ON rehearsal_sessions(expires_at, status)"),
]);}

function parse<T>(value:string|null,fallback:T):T{if(!value)return fallback;try{return JSON.parse(value) as T}catch{return fallback}}
function fromRow(row:SessionRow):RehearsalSession{return{id:row.id,repositoryId:row.repository_id,repositoryName:row.repository_name,incidentTemplateId:row.incident_template_id,difficulty:row.difficulty,mode:row.mode,timeLimitMinutes:row.time_limit_minutes,status:row.status,hintCount:row.hint_count,hypotheses:parse(row.hypotheses_json,[]),timeline:parse(row.timeline_json,[]),workspaceKey:row.workspace_key,ownerAccountId:row.owner_account_id,createdAt:row.created_at,startedAt:row.started_at,completedAt:row.completed_at,expiresAt:row.expires_at,score:row.score,validation:parse<ValidationResult|null>(row.validation_json,null),report:parse<RehearsalReport|null>(row.report_json,null)}}
async function ownerId(user:Exclude<SessionUser,null>){return(await ensureAccount(user.email,user.displayName)).id}
function event(type:string,summary:string,extra:Partial<TimelineEvent>={}):TimelineEvent{return{type,timestamp:new Date().toISOString(),summary,...extra}}

export async function createRehearsal(user:SessionUser,input:{repositoryId:string;repositoryAccessToken?:string|null;incidentTemplateId:string;difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED";mode:AccountMode;timeLimitMinutes:number}){
  await ensureRehearsalSchema();const repository=await getRepository(input.repositoryId,user,input.repositoryAccessToken);const source=await loadRepositoryFiles(repository);
  let generatedIncident:GeneratedIncidentBlueprint|undefined;let incidentName:string;
  if(input.incidentTemplateId.startsWith("custom:")){if(!user)throw new RehearsalError("AUTHENTICATION_REQUIRED","Sign in to open a team-authored incident.",401);try{generatedIncident=await customIncidentBlueprint(user,input.incidentTemplateId.slice(7),source,input.difficulty);incidentName=generatedIncident.template.name}catch(error){throw new RehearsalError("CUSTOM_INCIDENT_UNAVAILABLE",error instanceof Error?error.message:"The custom incident is unavailable.",422)}}else if(input.incidentTemplateId===GENERATED_INCIDENT_ID){try{generatedIncident=generateIncidentBlueprint(source,input.difficulty);incidentName=generatedIncident.template.name}catch(error){throw new RehearsalError("NO_INCIDENT_CANDIDATE",error instanceof Error?error.message:"No supported incident could be generated for this repository.",422)}}else{incidentName=scenarioFor(input.incidentTemplateId).template.name}
  const token=accessToken();const id=crypto.randomUUID();const now=new Date();const expiresAt=new Date(now.getTime()+Math.min(60,input.timeLimitMinutes+15)*60_000).toISOString();const owner=user?await ownerId(user):null;
  const timeline=[event("session_created",`Rehearsal created for ${incidentName}.`)];const workspaceKey=`sessions/${id}/workspace.json`;
  await repositoryBucket().put(workspaceKey,JSON.stringify({version:2,files:source,generatedIncident} satisfies WorkspaceEnvelope),{httpMetadata:{contentType:"application/json"},customMetadata:{sessionId:id,expiresAt}});
  await runtimeDatabase().prepare(`INSERT INTO rehearsal_sessions (id, owner_account_id, access_token_hash, repository_id, repository_name, incident_template_id, difficulty, mode, time_limit_minutes, status, hypotheses_json, timeline_json, workspace_key, created_at, expires_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'PREPARING', '[]', ?, ?, ?, ?)`).bind(id,owner,await sha256(token),repository.id,repository.name,input.incidentTemplateId,input.difficulty,input.mode,input.timeLimitMinutes,JSON.stringify(timeline),workspaceKey,now.toISOString(),expiresAt).run();
  const session=await getRehearsal(id,user,token);await trackRehearsalFunnel(session,"created",{language:String(repository.analysis.language??"Unknown")});return{session,accessToken:token};
}

async function rowFor(id:string){const row=await runtimeDatabase().prepare("SELECT * FROM rehearsal_sessions WHERE id = ?").bind(id).first<SessionRow>();if(!row)throw new RehearsalError("NOT_FOUND","Rehearsal not found.",404);return row}
export async function getRehearsal(id:string,user:SessionUser,token?:string|null):Promise<RehearsalSession>{await ensureRehearsalSchema();const row=await rowFor(id);const requesterId=user?await ownerId(user):null;let owned=Boolean(requesterId&&row.owner_account_id===requesterId);if(!owned&&requesterId){try{owned=Boolean(await runtimeDatabase().prepare("SELECT a.id FROM screening_attempts a JOIN screening_campaigns c ON c.id=a.campaign_id WHERE a.session_id=? AND c.owner_account_id=? LIMIT 1").bind(id,requesterId).first())}catch{/* screening schema is optional */}}const tokenMatches=token&&await sha256(token)===row.access_token_hash;if(!owned&&!tokenMatches)throw new RehearsalError("FORBIDDEN","Rehearsal access is not authorized.",403);const hardDeadline=row.started_at&&["ACTIVE","VALIDATING"].includes(row.status)?Date.parse(row.started_at)+row.time_limit_minutes*60_000:Date.parse(row.expires_at);if(row.status!=="COMPLETED"&&row.status!=="EXPIRED"&&hardDeadline<=Date.now()){if(row.workspace_key)await repositoryBucket().delete(row.workspace_key);await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'EXPIRED', workspace_key = NULL WHERE id = ?").bind(id).run();row.status="EXPIRED";row.workspace_key=null}return fromRow(row)}
async function persistTimeline(session:RehearsalSession,next:TimelineEvent[]){await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET timeline_json = ? WHERE id = ?").bind(JSON.stringify(next),session.id).run();session.timeline=next}
async function workspace(session:RehearsalSession):Promise<WorkspaceEnvelope>{if(!session.workspaceKey)throw new RehearsalError("WORKSPACE_NOT_READY","The rehearsal workspace is not ready.",409);const object=await repositoryBucket().get(session.workspaceKey);if(!object)throw new RehearsalError("WORKSPACE_MISSING","The rehearsal workspace has expired.",410);const parsed=JSON.parse(await object.text()) as{version?:number;files?:WorkspaceFile[];generatedIncident?:GeneratedIncidentBlueprint};if(!Array.isArray(parsed.files))throw new RehearsalError("WORKSPACE_INVALID","The rehearsal workspace is invalid.",500);return{version:2,files:parsed.files,generatedIncident:parsed.generatedIncident}}
async function saveWorkspace(session:RehearsalSession,envelope:WorkspaceEnvelope){if(!session.workspaceKey)throw new RehearsalError("WORKSPACE_NOT_READY","The rehearsal workspace is not ready.",409);await repositoryBucket().put(session.workspaceKey,JSON.stringify(envelope),{httpMetadata:{contentType:"application/json"},customMetadata:{sessionId:session.id,expiresAt:session.expiresAt}})}

export async function prepareRehearsal(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="PREPARING")throw new RehearsalError("INVALID_STATE","Only a preparing rehearsal can be prepared.",409);const envelope=await workspace(session);const files=envelope.generatedIncident?applyGeneratedIncident(envelope.files,envelope.generatedIncident):scenarioFor(session.incidentTemplateId).prepare(envelope.files);await saveWorkspace(session,{...envelope,files});const target=envelope.generatedIncident?.targetPath;const timeline=[...session.timeline,event("baseline_verified",target?`Repository baseline mapped; controlled fault injected at ${target}.`:"Clean source snapshot recorded and controlled fault verified.")];await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'READY', timeline_json = ? WHERE id = ?").bind(JSON.stringify(timeline),id).run();await trackRehearsalFunnel(session,"prepared");return getRehearsal(id,user,token)}
export async function startRehearsal(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="READY")throw new RehearsalError("INVALID_STATE","Only a ready rehearsal can be started.",409);const now=new Date();const expiresAt=new Date(now.getTime()+session.timeLimitMinutes*60_000).toISOString();await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'ACTIVE', started_at = ?, expires_at = ?, timeline_json = ? WHERE id = ?").bind(now.toISOString(),expiresAt,JSON.stringify([...session.timeline,event("incident_started","Incident briefing acknowledged.")]),id).run();await trackRehearsalFunnel(session,"started");return getRehearsal(id,user,token)}
export async function listFiles(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);return(await workspace(session)).files.map(file=>file.path)}
export async function readWorkspaceFile(id:string,path:string,user:SessionUser,token?:string|null){if(!isSafeArchiveEntry(path))throw new RehearsalError("INVALID_PATH","File path is invalid.",400);const session=await getRehearsal(id,user,token);const found=(await workspace(session)).files.find(file=>file.path===path);if(!found)throw new RehearsalError("FILE_NOT_FOUND","File not found.",404);await persistTimeline(session,[...session.timeline,event("file_opened",`Opened ${path}.`,{path})]);return found.content}
export async function writeWorkspaceFile(id:string,path:string,content:string,user:SessionUser,token?:string|null){if(!isSafeArchiveEntry(path)||content.length>1_000_000)throw new RehearsalError("INVALID_FILE","File update is invalid or too large.",400);const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Files can only be edited during an active rehearsal.",409);const envelope=await workspace(session);const found=envelope.files.find(file=>file.path===path);if(!found)throw new RehearsalError("FILE_NOT_FOUND","File not found.",404);if(found.content===content)return{path,content,changed:false};found.content=content;await saveWorkspace(session,envelope);await persistTimeline(session,[...session.timeline,event("file_edited",`Edited ${path}.`,{path})]);await trackRehearsalFunnel(session,"edited");return{path,content,changed:true}}
export async function runRehearsalCommand(id:string,commandId:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Commands require an active rehearsal.",409);if(!["run-tests","run-lint","run-build","migration-status","check-health","restart-service"].includes(commandId))throw new RehearsalError("COMMAND_NOT_APPROVED","Command is not approved.",403);const envelope=await workspace(session);const generated=envelope.generatedIncident;const staticScenario=generated?null:scenarioFor(session.incidentTemplateId);const validation=generated?evaluateGeneratedIncident(generated,envelope.files,{timeline:session.timeline,hypotheses:session.hypotheses,hintCount:session.hintCount}):staticScenario!.evaluate(envelope.files,session.hintCount);let output="";let exitCode=0;if(commandId==="run-tests"){exitCode=validation.passed?0:1;const failed=validation.checks.filter(check=>check.status==="failed"&&!check.hidden);output=validation.passed?`✓ repository baseline contract\n✓ incident behavior contract\n\n2 passed`:`✓ repository baseline loaded\n${failed.map(check=>`✗ ${check.name}`).join("\n")||"✗ incident behavior contract"}\n\n${failed.length||1} failed`;}else if(commandId==="check-health")output=validation.passed?"application HEALTHY\ndependency HEALTHY":"application DEGRADED\ndependency state available in evidence";else if(commandId==="migration-status")output=(generated?.databaseEvidence??staticScenario!.databaseEvidence).join("\n");else if(commandId==="restart-service")output="Service restarted inside the isolated rehearsal boundary.";else output=validation.passed?"Repository contract completed successfully.":"Repository contract completed with incident-related failures.";await persistTimeline(session,[...session.timeline,event("command_run",`Ran approved command ${commandId}.`,{commandId})]);await trackRehearsalFunnel(session,"command");return{commandId,exitCode,output}}
export async function getEvidence(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);const envelope=await workspace(session);if(envelope.generatedIncident){const incident=envelope.generatedIncident;return{logs:incident.logs,database:incident.databaseEvidence,health:incident.healthEvidence,briefing:incident.template.briefing,targetPath:incident.targetPath,hints:incident.template.hints,generated:{engine:incident.generator,confidence:incident.candidate.confidence,reason:incident.candidate.reason}}}const scenario=scenarioFor(session.incidentTemplateId);return{logs:scenario.logs,database:scenario.databaseEvidence,health:scenario.healthEvidence,briefing:scenario.template.briefing,targetPath:scenario.targetPath,hints:scenario.template.hints}}
export async function recordEvidenceAccess(id:string,source:"logs"|"database",user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Evidence can only be inspected during an active rehearsal.",409);await persistTimeline(session,[...session.timeline,event("evidence_viewed",source==="logs"?"Inspected correlated incident logs.":"Compared affected repository state.",{commandId:`evidence-${source}`})]);await trackRehearsalFunnel(session,"evidence")}
export async function addHypothesis(id:string,hypothesis:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE"||!hypothesis.trim()||hypothesis.length>500)throw new RehearsalError("INVALID_HYPOTHESIS","Hypothesis is invalid.",400);const hypotheses=[...session.hypotheses,hypothesis.trim()];const timeline=[...session.timeline,event("hypothesis_added","Recorded a root-cause hypothesis.")];await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET hypotheses_json = ?, timeline_json = ? WHERE id = ?").bind(JSON.stringify(hypotheses),JSON.stringify(timeline),id).run();return{hypotheses}}
export async function requestHint(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Hints require an active rehearsal.",409);if(session.mode==="INTERVIEW")throw new RehearsalError("HINTS_DISABLED","Hints are disabled in interview mode.",403);const envelope=await workspace(session);const hints=envelope.generatedIncident?.template.hints??scenarioFor(session.incidentTemplateId).template.hints;const next=Math.min(session.hintCount+1,hints.length);const timeline=[...session.timeline,event("hint_requested",`Requested hint level ${next}.`)];await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET hint_count = ?, timeline_json = ? WHERE id = ?").bind(next,JSON.stringify(timeline),id).run();return{level:next,hint:hints[next-1],penalty:hintPenaltyForLevel(next)}}
function hintPenaltyForLevel(level:number){return[0,1,2,4,7][level]??7}
function reportFor(session:RehearsalSession,validation:ValidationResult,template:IncidentTemplate,generated?:GeneratedIncidentBlueprint):RehearsalReport{const passed=validation.passed;const evidence=[...new Set(session.timeline.filter(item=>["file_opened","command_run","evidence_viewed","hypothesis_added"].includes(item.type)).map(item=>item.summary))];const prevention=generated?preventionForGeneratedIncident(generated):template.category==="database"?["Preserve null-safe transitions while data constraints roll out.","Add regression fixtures for every data-creation path."]:template.category==="configuration"?["Validate runtime configuration before accepting traffic.","Exercise quality commands and service discovery in the deployment boundary."]:["Validate external responses before parsing success payloads.","Add contract fixtures for error, partial, and renamed responses."];const markdown=`# ${template.name} — After-action report\n\n**Score:** ${validation.score}/100  \n**Outcome:** ${passed?"Resolved":"Unresolved"}\n\n## Root cause\n${template.intendedRootCause}\n\n## Skill breakdown\n${validation.breakdown.map(item=>`- ${item.label}: ${item.earned}/${item.possible}${item.signals?.length?`\n${item.signals.map(signal=>`  - ${signal}`).join("\n")}`:""}`).join("\n")}\n\n## Validation\n${validation.checks.map(check=>`- ${check.status==="passed"?"✓":"×"} ${check.name}: ${check.detail}`).join("\n")}\n\n## Prevention\n${prevention.map(item=>`- ${item}`).join("\n")}`;return{title:`${template.name} — After-action report`,rootCause:template.intendedRootCause,summary:passed?"The submitted workspace repaired the repository-derived failure and preserved the baseline contract.":"The submitted workspace still fails one or more repository-derived behavior contracts.",evidenceUsed:evidence,missedEvidence:evidence.length<3?["Use multiple evidence sources and record a supported root-cause hypothesis before editing."]:[],prevention,score:validation.score,passed,markdown,aiEnhanced:false}}
export async function submitRehearsal(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Only an active rehearsal can be submitted.",409);await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'VALIDATING' WHERE id = ?").bind(id).run();const envelope=await workspace(session);const generated=envelope.generatedIncident;const scenario=generated?null:scenarioFor(session.incidentTemplateId);const template=generated?.template??scenario!.template;const rawValidation=generated?evaluateGeneratedIncident(generated,envelope.files,{timeline:session.timeline,hypotheses:session.hypotheses,hintCount:session.hintCount}):scenario!.evaluate(envelope.files,session.hintCount);const workspaceEdited=generated?hasGeneratedWorkspaceEdits(generated,envelope.files):envelope.files.find(file=>file.path===scenario!.targetPath)?.content!==scenario!.injectedSource;const validation=normalizeSubmissionScore(rawValidation,workspaceEdited);const report=await enhanceReport(reportFor(session,validation,template,generated),session,validation);const now=new Date().toISOString();const durationSeconds=Math.max(0,Math.round((Date.parse(now)-Date.parse(session.startedAt??session.createdAt))/1000));if(session.workspaceKey)await repositoryBucket().delete(session.workspaceKey);await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'COMPLETED', workspace_key = NULL, score = ?, validation_json = ?, report_json = ?, completed_at = ?, timeline_json = ? WHERE id = ?").bind(validation.score,JSON.stringify(validation),JSON.stringify(report),now,JSON.stringify([...session.timeline,event("repair_submitted",`Repair submitted with score ${validation.score}.`)]),id).run();if(user)await saveAccountRehearsal(user.email,user.displayName,{id:session.id,incidentTemplateId:session.incidentTemplateId,incidentName:template.name,repositoryName:session.repositoryName,mode:session.mode,status:validation.passed?"COMPLETED":"UNRESOLVED",score:validation.score,durationMinutes:Math.max(1,Math.ceil(durationSeconds/60)),hintsUsed:session.hintCount,completedAt:now});await trackRehearsalFunnel(session,"completed",{score:validation.score});const dailyLeaderboard=session.repositoryId===DAILY_REPOSITORY_ID?await recordDailyLeaderboardResult(user,{sessionId:session.id,dateKey:dailyChallenge(new Date(session.createdAt)).dateKey,score:validation.score,durationSeconds,completedAt:now}):null;return{session:await getRehearsal(id,user,token),validation,report,dailyLeaderboard}}

export async function cleanupExpiredRehearsals(){await ensureRehearsalSchema();const now=new Date().toISOString();const result=await runtimeDatabase().prepare("SELECT id, workspace_key FROM rehearsal_sessions WHERE status != 'COMPLETED' AND expires_at <= ? LIMIT 100").bind(now).all<{id:string;workspace_key:string|null}>();for(const row of result.results??[]){if(row.workspace_key)await repositoryBucket().delete(row.workspace_key);await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'EXPIRED', workspace_key = NULL WHERE id = ?").bind(row.id).run()}return result.results?.length??0}

export class RehearsalError extends Error{constructor(public readonly code:string,message:string,public readonly status:number){super(message)}}
