import { ensureAccount, ensureAccountSchema } from "../accounts/account-service";
import { saveAccountRehearsal } from "../accounts/account-service";
import { getRepository, loadRepositoryFiles, type RepositoryUser } from "../repositories/repository-service";
import { isSafeArchiveEntry } from "../security/path-validation";
import { accessToken, repositoryBucket, runtimeDatabase, sha256 } from "../storage/runtime";
import { scenarioFor } from "./scenarios";
import type { RehearsalReport, RehearsalSession, RehearsalStatus, TimelineEvent, WorkspaceFile } from "./types";
import type { AccountMode } from "../accounts/types";
import type { ValidationResult } from "../types";
import { enhanceReport } from "../ai/report-enhancer";

type SessionRow = { id:string;owner_account_id:string|null;access_token_hash:string;repository_id:string;repository_name:string;incident_template_id:string;difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED";mode:AccountMode;time_limit_minutes:number;status:RehearsalStatus;hint_count:number;hypotheses_json:string;timeline_json:string;workspace_key:string|null;score:number|null;validation_json:string|null;report_json:string|null;created_at:string;started_at:string|null;completed_at:string|null;expires_at:string };
export type SessionUser=RepositoryUser;

export async function ensureRehearsalSchema(){await ensureAccountSchema();const db=runtimeDatabase();await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS rehearsal_sessions (
    id TEXT PRIMARY KEY NOT NULL, owner_account_id TEXT, access_token_hash TEXT NOT NULL, repository_id TEXT NOT NULL,
    repository_name TEXT NOT NULL, incident_template_id TEXT NOT NULL, difficulty TEXT NOT NULL, mode TEXT NOT NULL,
    time_limit_minutes INTEGER NOT NULL, status TEXT NOT NULL, hint_count INTEGER NOT NULL DEFAULT 0,
    hypotheses_json TEXT NOT NULL DEFAULT '[]', timeline_json TEXT NOT NULL DEFAULT '[]', workspace_key TEXT,
    score INTEGER, validation_json TEXT, report_json TEXT, created_at TEXT NOT NULL, started_at TEXT, completed_at TEXT,
    expires_at TEXT NOT NULL, FOREIGN KEY (owner_account_id) REFERENCES accounts(id) ON DELETE CASCADE
  )`),
  db.prepare("CREATE INDEX IF NOT EXISTS rehearsal_sessions_owner_date_idx ON rehearsal_sessions(owner_account_id, created_at DESC)"),
  db.prepare("CREATE INDEX IF NOT EXISTS rehearsal_sessions_expiry_idx ON rehearsal_sessions(expires_at, status)"),
]);}

function parse<T>(value:string|null,fallback:T):T{if(!value)return fallback;try{return JSON.parse(value) as T}catch{return fallback}}
function fromRow(row:SessionRow):RehearsalSession{return{id:row.id,repositoryId:row.repository_id,repositoryName:row.repository_name,incidentTemplateId:row.incident_template_id,difficulty:row.difficulty,mode:row.mode,timeLimitMinutes:row.time_limit_minutes,status:row.status,hintCount:row.hint_count,hypotheses:parse(row.hypotheses_json,[]),timeline:parse(row.timeline_json,[]),workspaceKey:row.workspace_key,ownerAccountId:row.owner_account_id,createdAt:row.created_at,startedAt:row.started_at,completedAt:row.completed_at,expiresAt:row.expires_at,score:row.score,validation:parse<ValidationResult|null>(row.validation_json,null),report:parse<RehearsalReport|null>(row.report_json,null)}}
async function ownerId(user:Exclude<SessionUser,null>){return(await ensureAccount(user.email,user.displayName)).id}
function event(type:string,summary:string,extra:Partial<TimelineEvent>={}):TimelineEvent{return{type,timestamp:new Date().toISOString(),summary,...extra}}

export async function createRehearsal(user:SessionUser,input:{repositoryId:string;repositoryAccessToken?:string|null;incidentTemplateId:string;difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED";mode:AccountMode;timeLimitMinutes:number}){
  await ensureRehearsalSchema();const repository=await getRepository(input.repositoryId,user,input.repositoryAccessToken);const scenario=scenarioFor(input.incidentTemplateId);
  const token=accessToken();const id=crypto.randomUUID();const now=new Date();const expiresAt=new Date(now.getTime()+Math.min(60,input.timeLimitMinutes+15)*60_000).toISOString();const owner=user?await ownerId(user):null;
  const timeline=[event("session_created",`Rehearsal created for ${scenario.template.name}.`)];const workspaceKey=`sessions/${id}/workspace.json`;const source=await loadRepositoryFiles(repository);
  await repositoryBucket().put(workspaceKey,JSON.stringify({version:1,files:source}),{httpMetadata:{contentType:"application/json"},customMetadata:{sessionId:id,expiresAt}});
  await runtimeDatabase().prepare(`INSERT INTO rehearsal_sessions (id, owner_account_id, access_token_hash, repository_id, repository_name, incident_template_id, difficulty, mode, time_limit_minutes, status, hypotheses_json, timeline_json, workspace_key, created_at, expires_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'PREPARING', '[]', ?, ?, ?, ?)`).bind(id,owner,await sha256(token),repository.id,repository.name,input.incidentTemplateId,input.difficulty,input.mode,input.timeLimitMinutes,JSON.stringify(timeline),workspaceKey,now.toISOString(),expiresAt).run();
  return{session:await getRehearsal(id,user,token),accessToken:token};
}

async function rowFor(id:string){const row=await runtimeDatabase().prepare("SELECT * FROM rehearsal_sessions WHERE id = ?").bind(id).first<SessionRow>();if(!row)throw new RehearsalError("NOT_FOUND","Rehearsal not found.",404);return row}
export async function getRehearsal(id:string,user:SessionUser,token?:string|null):Promise<RehearsalSession>{await ensureRehearsalSchema();const row=await rowFor(id);const owned=user&&row.owner_account_id===await ownerId(user);const tokenMatches=token&&await sha256(token)===row.access_token_hash;if(!owned&&!tokenMatches)throw new RehearsalError("FORBIDDEN","Rehearsal access is not authorized.",403);const hardDeadline=row.started_at&&["ACTIVE","VALIDATING"].includes(row.status)?Date.parse(row.started_at)+row.time_limit_minutes*60_000:Date.parse(row.expires_at);if(row.status!=="COMPLETED"&&row.status!=="EXPIRED"&&hardDeadline<=Date.now()){if(row.workspace_key)await repositoryBucket().delete(row.workspace_key);await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'EXPIRED', workspace_key = NULL WHERE id = ?").bind(id).run();row.status="EXPIRED";row.workspace_key=null}return fromRow(row)}
async function persistTimeline(session:RehearsalSession,next:TimelineEvent[]){await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET timeline_json = ? WHERE id = ?").bind(JSON.stringify(next),session.id).run();session.timeline=next}
async function workspace(session:RehearsalSession):Promise<WorkspaceFile[]>{if(!session.workspaceKey)throw new RehearsalError("WORKSPACE_NOT_READY","The rehearsal workspace is not ready.",409);const object=await repositoryBucket().get(session.workspaceKey);if(!object)throw new RehearsalError("WORKSPACE_MISSING","The rehearsal workspace has expired.",410);const parsed=JSON.parse(await object.text()) as{files?:WorkspaceFile[]};if(!Array.isArray(parsed.files))throw new RehearsalError("WORKSPACE_INVALID","The rehearsal workspace is invalid.",500);return parsed.files}
async function saveWorkspace(session:RehearsalSession,files:WorkspaceFile[]){if(!session.workspaceKey)throw new RehearsalError("WORKSPACE_NOT_READY","The rehearsal workspace is not ready.",409);await repositoryBucket().put(session.workspaceKey,JSON.stringify({version:1,files}),{httpMetadata:{contentType:"application/json"},customMetadata:{sessionId:session.id,expiresAt:session.expiresAt}})}

export async function prepareRehearsal(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="PREPARING")throw new RehearsalError("INVALID_STATE","Only a preparing rehearsal can be prepared.",409);const source=await workspace(session);const scenario=scenarioFor(session.incidentTemplateId);const files=scenario.prepare(source);await saveWorkspace(session,files);const timeline=[...session.timeline,event("baseline_verified","Clean source snapshot recorded and controlled fault verified.")];await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'READY', timeline_json = ? WHERE id = ?").bind(JSON.stringify(timeline),id).run();return getRehearsal(id,user,token)}
export async function startRehearsal(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="READY")throw new RehearsalError("INVALID_STATE","Only a ready rehearsal can be started.",409);const now=new Date();const expiresAt=new Date(now.getTime()+session.timeLimitMinutes*60_000).toISOString();await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'ACTIVE', started_at = ?, expires_at = ?, timeline_json = ? WHERE id = ?").bind(now.toISOString(),expiresAt,JSON.stringify([...session.timeline,event("incident_started","Incident briefing acknowledged.")]),id).run();return getRehearsal(id,user,token)}
export async function listFiles(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);return(await workspace(session)).map(file=>file.path)}
export async function readWorkspaceFile(id:string,path:string,user:SessionUser,token?:string|null){if(!isSafeArchiveEntry(path))throw new RehearsalError("INVALID_PATH","File path is invalid.",400);const session=await getRehearsal(id,user,token);const found=(await workspace(session)).find(file=>file.path===path);if(!found)throw new RehearsalError("FILE_NOT_FOUND","File not found.",404);await persistTimeline(session,[...session.timeline,event("file_opened",`Opened ${path}.`,{path})]);return found.content}
export async function writeWorkspaceFile(id:string,path:string,content:string,user:SessionUser,token?:string|null){if(!isSafeArchiveEntry(path)||content.length>1_000_000)throw new RehearsalError("INVALID_FILE","File update is invalid or too large.",400);const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Files can only be edited during an active rehearsal.",409);const files=await workspace(session);const found=files.find(file=>file.path===path);if(!found)throw new RehearsalError("FILE_NOT_FOUND","File not found.",404);found.content=content;await saveWorkspace(session,files);await persistTimeline(session,[...session.timeline,event("file_edited",`Edited ${path}.`,{path})]);return{path,content}}
export async function runRehearsalCommand(id:string,commandId:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Commands require an active rehearsal.",409);if(!["run-tests","run-lint","run-build","migration-status","check-health","restart-service"].includes(commandId))throw new RehearsalError("COMMAND_NOT_APPROVED","Command is not approved.",403);const scenario=scenarioFor(session.incidentTemplateId);const validation=scenario.evaluate(await workspace(session),session.hintCount);let output="";let exitCode=0;if(commandId==="run-tests"){exitCode=validation.passed?0:1;output=validation.passed?`✓ public incident regression\n✓ baseline behavior\n\n2 passed`:`✓ baseline behavior\n✗ incident regression\n\n1 failed, 1 passed`;}else if(commandId==="check-health")output=validation.passed?"service HEALTHY\ndependency HEALTHY":"service DEGRADED\ndependency HEALTHY";else if(commandId==="migration-status")output=scenario.databaseEvidence.join("\n");else if(commandId==="restart-service")output="Service restarted inside the isolated rehearsal boundary.";else output=validation.passed?"Command completed successfully.":"Command completed with incident-related failures.";await persistTimeline(session,[...session.timeline,event("command_run",`Ran approved command ${commandId}.`,{commandId})]);return{commandId,exitCode,output}}
export async function getEvidence(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);const scenario=scenarioFor(session.incidentTemplateId);return{logs:scenario.logs,database:scenario.databaseEvidence,health:scenario.healthEvidence,briefing:scenario.template.briefing,targetPath:scenario.targetPath,hints:scenario.template.hints}}
export async function addHypothesis(id:string,hypothesis:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE"||!hypothesis.trim()||hypothesis.length>500)throw new RehearsalError("INVALID_HYPOTHESIS","Hypothesis is invalid.",400);const hypotheses=[...session.hypotheses,hypothesis.trim()];const timeline=[...session.timeline,event("hypothesis_added","Recorded a root-cause hypothesis.")];await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET hypotheses_json = ?, timeline_json = ? WHERE id = ?").bind(JSON.stringify(hypotheses),JSON.stringify(timeline),id).run();return{hypotheses}}
export async function requestHint(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Hints require an active rehearsal.",409);if(session.mode==="INTERVIEW")throw new RehearsalError("HINTS_DISABLED","Hints are disabled in interview mode.",403);const scenario=scenarioFor(session.incidentTemplateId);const next=Math.min(session.hintCount+1,scenario.template.hints.length);const timeline=[...session.timeline,event("hint_requested",`Requested hint level ${next}.`)];await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET hint_count = ?, timeline_json = ? WHERE id = ?").bind(next,JSON.stringify(timeline),id).run();return{level:next,hint:scenario.template.hints[next-1],penalty:hintPenaltyForLevel(next)}}
function hintPenaltyForLevel(level:number){return[0,1,2,4,7][level]??7}
function reportFor(session:RehearsalSession,validation:ValidationResult):RehearsalReport{const scenario=scenarioFor(session.incidentTemplateId);const passed=validation.passed;const evidence=session.timeline.filter(item=>["file_opened","command_run"].includes(item.type)).map(item=>item.summary);const prevention=scenario.template.category==="database"?["Use expand/backfill/contract migrations.","Test every data-creation path against legacy snapshots."]:scenario.template.category==="configuration"?["Validate runtime configuration at startup.","Test service discovery inside the deployment network."]:["Validate third-party payloads at the boundary.","Add contract fixtures for partial and renamed fields."];const markdown=`# ${scenario.template.name} — After-action report\n\n**Score:** ${validation.score}/100  \n**Outcome:** ${passed?"Resolved":"Unresolved"}\n\n## Root cause\n${scenario.template.intendedRootCause}\n\n## Validation\n${validation.checks.map(check=>`- ${check.status==="passed"?"✓":"×"} ${check.name}: ${check.detail}`).join("\n")}\n\n## Prevention\n${prevention.map(item=>`- ${item}`).join("\n")}`;return{title:`${scenario.template.name} — After-action report`,rootCause:scenario.template.intendedRootCause,summary:passed?"The repair addressed the root cause and passed deterministic validation.":"The repair did not yet satisfy all deterministic checks.",evidenceUsed:evidence,missedEvidence:evidence.length<2?["Inspect more than one evidence source before submitting."]:[],prevention,score:validation.score,passed,markdown,aiEnhanced:false}}
export async function submitRehearsal(id:string,user:SessionUser,token?:string|null){const session=await getRehearsal(id,user,token);if(session.status!=="ACTIVE")throw new RehearsalError("INVALID_STATE","Only an active rehearsal can be submitted.",409);await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'VALIDATING' WHERE id = ?").bind(id).run();const scenario=scenarioFor(session.incidentTemplateId);const validation=scenario.evaluate(await workspace(session),session.hintCount);const report=await enhanceReport(reportFor(session,validation),session,validation);const now=new Date().toISOString();if(session.workspaceKey)await repositoryBucket().delete(session.workspaceKey);await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'COMPLETED', workspace_key = NULL, score = ?, validation_json = ?, report_json = ?, completed_at = ?, timeline_json = ? WHERE id = ?").bind(validation.score,JSON.stringify(validation),JSON.stringify(report),now,JSON.stringify([...session.timeline,event("repair_submitted",`Repair submitted with score ${validation.score}.`)]),id).run();if(user)await saveAccountRehearsal(user.email,user.displayName,{id:session.id,incidentTemplateId:session.incidentTemplateId,incidentName:scenario.template.name,repositoryName:session.repositoryName,mode:session.mode,status:validation.passed?"COMPLETED":"UNRESOLVED",score:validation.score,durationMinutes:Math.max(1,Math.ceil((Date.now()-Date.parse(session.startedAt??session.createdAt))/60_000)),hintsUsed:session.hintCount,completedAt:now});return{session:await getRehearsal(id,user,token),validation,report}}

export async function cleanupExpiredRehearsals(){await ensureRehearsalSchema();const now=new Date().toISOString();const result=await runtimeDatabase().prepare("SELECT id, workspace_key FROM rehearsal_sessions WHERE status != 'COMPLETED' AND expires_at <= ? LIMIT 100").bind(now).all<{id:string;workspace_key:string|null}>();for(const row of result.results??[]){if(row.workspace_key)await repositoryBucket().delete(row.workspace_key);await runtimeDatabase().prepare("UPDATE rehearsal_sessions SET status = 'EXPIRED', workspace_key = NULL WHERE id = ?").bind(row.id).run()}return result.results?.length??0}

export class RehearsalError extends Error{constructor(public readonly code:string,message:string,public readonly status:number){super(message)}}
