import type { AuthenticatedUser } from "../auth/auth-service";
import { ensureAccount } from "../accounts/account-service";
import { accessToken, runtimeDatabase, sha256 } from "../storage/runtime";
import { getTeamViewerContext, TeamServiceError } from "../team/team-service";
import { createRehearsal } from "../rehearsals/session-service";
import { incidents } from "../data";

type CampaignRow={id:string;team_id:string;owner_account_id:string;title:string;repository_id:string;repository_name:string;incident_template_id:string;incident_name:string;public_token_hash:string;public_token:string;active:number;created_at:string};
export async function ensureRecruitingSchema(){await runtimeDatabase().batch([runtimeDatabase().prepare(`CREATE TABLE IF NOT EXISTS screening_campaigns (id TEXT PRIMARY KEY NOT NULL, team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE, owner_account_id TEXT NOT NULL, title TEXT NOT NULL, repository_id TEXT NOT NULL, repository_name TEXT NOT NULL, incident_template_id TEXT NOT NULL, incident_name TEXT NOT NULL, public_token_hash TEXT NOT NULL UNIQUE, public_token TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)`),runtimeDatabase().prepare(`CREATE TABLE IF NOT EXISTS screening_attempts (id TEXT PRIMARY KEY NOT NULL, campaign_id TEXT NOT NULL REFERENCES screening_campaigns(id) ON DELETE CASCADE, session_id TEXT NOT NULL UNIQUE, candidate_name TEXT NOT NULL, candidate_email TEXT NOT NULL, created_at TEXT NOT NULL)`)])}
export async function createCampaign(user:AuthenticatedUser,input:{title:string;repositoryId:string;repositoryName:string;incidentTemplateId:string}){await ensureRecruitingSchema();const{team,viewerRole}=await getTeamViewerContext(user,true);if(viewerRole!=="OWNER")throw new TeamServiceError("OWNER_REQUIRED","Only a team manager can create candidate screens.",403);const profile=await ensureAccount(user.email,user.displayName);const incident=incidents.find(item=>item.id===input.incidentTemplateId);if(!incident)throw new TeamServiceError("INCIDENT_NOT_FOUND","Choose a supported screening incident.",422);const token=accessToken(),id=crypto.randomUUID(),now=new Date().toISOString();await runtimeDatabase().prepare("INSERT INTO screening_campaigns (id,team_id,owner_account_id,title,repository_id,repository_name,incident_template_id,incident_name,public_token_hash,public_token,active,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,1,?)").bind(id,team.id,profile.id,input.title,input.repositoryId,input.repositoryName,incident.id,incident.name,await sha256(token),token,now).run();return{id,token}}
export async function listCampaigns(user:AuthenticatedUser){await ensureRecruitingSchema();const{team,viewerRole}=await getTeamViewerContext(user);if(viewerRole!=="OWNER")throw new TeamServiceError("OWNER_REQUIRED","Only the team manager can view candidate results.",403);const campaigns=await runtimeDatabase().prepare("SELECT * FROM screening_campaigns WHERE team_id=? ORDER BY created_at DESC").bind(team.id).all<CampaignRow>();const attempts=await runtimeDatabase().prepare(`SELECT a.id,a.campaign_id,a.candidate_name,a.candidate_email,a.created_at,s.id session_id,s.status,s.score,s.completed_at,s.validation_json FROM screening_attempts a JOIN screening_campaigns c ON c.id=a.campaign_id LEFT JOIN rehearsal_sessions s ON s.id=a.session_id WHERE c.team_id=? ORDER BY a.created_at DESC`).bind(team.id).all<Record<string,unknown>>();return{campaigns:(campaigns.results??[]).map(c=>({id:c.id,title:c.title,repositoryName:c.repository_name,incidentName:c.incident_name,token:c.public_token,active:Boolean(c.active),createdAt:c.created_at})),attempts:(attempts.results??[]).map(row=>{const{validation_json,...rest}=row;return{...rest,breakdown:parseAttemptBreakdown(validation_json as string|null)}})}}
function parseAttemptBreakdown(value:string|null):{label:string;earned:number;possible:number;signals?:string[]}[]|null{if(!value)return null;try{const parsed=JSON.parse(value) as{breakdown?:{label:string;earned:number;possible:number;signals?:string[]}[]};return parsed.breakdown??null}catch{return null}}
export async function campaignForToken(token:string){await ensureRecruitingSchema();return runtimeDatabase().prepare("SELECT * FROM screening_campaigns WHERE public_token_hash=? AND active=1").bind(await sha256(token)).first<CampaignRow>()}
export async function startCandidateScreen(token:string,input:{name:string;email:string}){const campaign=await campaignForToken(token);if(!campaign)throw new TeamServiceError("SCREEN_NOT_FOUND","This candidate exercise is unavailable or closed.",404);const created=await createRehearsal(null,{repositoryId:campaign.repository_id,incidentTemplateId:campaign.incident_template_id,difficulty:"INTERMEDIATE",mode:"INTERVIEW",timeLimitMinutes:45});await runtimeDatabase().prepare("INSERT INTO screening_attempts (id,campaign_id,session_id,candidate_name,candidate_email,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),campaign.id,created.session.id,input.name,input.email.toLowerCase(),new Date().toISOString()).run();return created}
