import type { AuthenticatedUser } from "../auth/auth-service";
import type { WorkspaceFile } from "../rehearsals/types";
import { getRepository, loadRepositoryFiles } from "../repositories/repository-service";
import { runtimeDatabase } from "../storage/runtime";
import { getTeamViewerContext, TeamServiceError } from "../team/team-service";
import type { GeneratedIncidentBlueprint, IncidentCandidate } from "./brain";

export type CustomIncident = { id:string;teamId:string;repositoryId:string;repositoryName:string;title:string;signal:string;rootCause:string;targetPath:string;safeSnippet:string;faultySnippet:string;evidence:string[];validationContract:string;objective:string;status:"DRAFT"|"PUBLISHED";sourceType:"MANUAL"|"GIT_DIFF"|"PAGERDUTY"|"DATADOG"|"JIRA";sourceRef:string|null;createdAt:string;updatedAt:string };
type Row={id:string;team_id:string;repository_id:string;repository_name:string;title:string;signal:string;root_cause:string;target_path:string;safe_snippet:string;faulty_snippet:string;evidence_json:string;validation_contract:string;objective:string;status:"DRAFT"|"PUBLISHED";source_type:CustomIncident["sourceType"];source_ref:string|null;created_at:string;updated_at:string};
const fromRow=(r:Row):CustomIncident=>({id:r.id,teamId:r.team_id,repositoryId:r.repository_id,repositoryName:r.repository_name,title:r.title,signal:r.signal,rootCause:r.root_cause,targetPath:r.target_path,safeSnippet:r.safe_snippet,faultySnippet:r.faulty_snippet,evidence:JSON.parse(r.evidence_json) as string[],validationContract:r.validation_contract,objective:r.objective,status:r.status,sourceType:r.source_type,sourceRef:r.source_ref,createdAt:r.created_at,updatedAt:r.updated_at});

export async function ensureCustomIncidentSchema(){await runtimeDatabase().prepare(`CREATE TABLE IF NOT EXISTS custom_incidents (
  id TEXT PRIMARY KEY NOT NULL, team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE, repository_id TEXT NOT NULL,
  repository_name TEXT NOT NULL, title TEXT NOT NULL, signal TEXT NOT NULL, root_cause TEXT NOT NULL, target_path TEXT NOT NULL,
  safe_snippet TEXT NOT NULL, faulty_snippet TEXT NOT NULL, evidence_json TEXT NOT NULL, validation_contract TEXT NOT NULL,
  objective TEXT NOT NULL, status TEXT NOT NULL, source_type TEXT NOT NULL, source_ref TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
)`).run()}

export async function listCustomIncidents(user:AuthenticatedUser){await ensureCustomIncidentSchema();const {team}=await getTeamViewerContext(user);const rows=await runtimeDatabase().prepare("SELECT * FROM custom_incidents WHERE team_id=? ORDER BY updated_at DESC").bind(team.id).all<Row>();return (rows.results??[]).map(fromRow)}

export async function saveCustomIncident(user:AuthenticatedUser,input:Omit<CustomIncident,"id"|"teamId"|"repositoryName"|"status"|"createdAt"|"updatedAt">){await ensureCustomIncidentSchema();const {team,viewerRole}=await getTeamViewerContext(user,true);if(viewerRole!=="OWNER")throw new TeamServiceError("OWNER_REQUIRED","Only the team manager can author incidents.",403);const repo=await getRepository(input.repositoryId,user,null);const files=await loadRepositoryFiles(repo);const target=files.find(file=>file.path===input.targetPath);if(!target)throw new TeamServiceError("TARGET_NOT_FOUND","The target path is not present in the selected repository.",422);if(!target.content.includes(input.safeSnippet))throw new TeamServiceError("BASELINE_NOT_FOUND","The known-good snippet must exactly match text in the target file.",422);if(input.safeSnippet===input.faultySnippet)throw new TeamServiceError("INVALID_INJECTION","The faulty snippet must differ from the known-good snippet.",422);const id=crypto.randomUUID(),now=new Date().toISOString();await runtimeDatabase().prepare(`INSERT INTO custom_incidents (id,team_id,repository_id,repository_name,title,signal,root_cause,target_path,safe_snippet,faulty_snippet,evidence_json,validation_contract,objective,status,source_type,source_ref,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'DRAFT',?,?,?,?)`).bind(id,team.id,repo.id,repo.name,input.title,input.signal,input.rootCause,input.targetPath,input.safeSnippet,input.faultySnippet,JSON.stringify(input.evidence),input.validationContract,input.objective,input.sourceType,input.sourceRef,now,now).run();return getCustomIncident(user,id,false)}

export async function updateCustomIncidentStatus(user:AuthenticatedUser,id:string,status:"PUBLISHED"|"DRAFT"){await ensureCustomIncidentSchema();const {team,viewerRole}=await getTeamViewerContext(user);if(viewerRole!=="OWNER")throw new TeamServiceError("OWNER_REQUIRED","Only the team manager can publish incidents.",403);const result=await runtimeDatabase().prepare("UPDATE custom_incidents SET status=?,updated_at=? WHERE id=? AND team_id=?").bind(status,new Date().toISOString(),id,team.id).run();if(!result.meta?.changes)throw new TeamServiceError("INCIDENT_NOT_FOUND","The custom incident could not be found.",404);return getCustomIncident(user,id,false)}
export async function deleteCustomIncident(user:AuthenticatedUser,id:string){const {team,viewerRole}=await getTeamViewerContext(user);if(viewerRole!=="OWNER")throw new TeamServiceError("OWNER_REQUIRED","Only the team manager can delete incidents.",403);await ensureCustomIncidentSchema();await runtimeDatabase().prepare("DELETE FROM custom_incidents WHERE id=? AND team_id=?").bind(id,team.id).run();return{deleted:true}}
export async function getCustomIncident(user:AuthenticatedUser,id:string,publishedOnly=true){await ensureCustomIncidentSchema();const {team}=await getTeamViewerContext(user);const row=await runtimeDatabase().prepare(`SELECT * FROM custom_incidents WHERE id=? AND team_id=? ${publishedOnly?"AND status='PUBLISHED'":""}`).bind(id,team.id).first<Row>();if(!row)throw new TeamServiceError("INCIDENT_NOT_FOUND","The custom incident could not be found.",404);return fromRow(row)}

function hash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,"0")}
export async function customIncidentBlueprint(user:{email:string;displayName:string},id:string,files:WorkspaceFile[],difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED"):Promise<GeneratedIncidentBlueprint>{const authUser:AuthenticatedUser={...user,fullName:user.displayName,provider:"chatgpt"};const incident=await getCustomIncident(authUser,id);const target=files.find(file=>file.path===incident.targetPath);if(!target||!target.content.includes(incident.safeSnippet))throw new TeamServiceError("BASELINE_CHANGED","The repository no longer contains this incident's approved baseline snippet.",409);const candidate:IncidentCandidate={id:`custom-${id}`,kind:"language-fallback",name:incident.title,category:"external_dependency",targetPath:incident.targetPath,confidence:1,reason:"Manager-reviewed custom incident contract.",before:incident.safeSnippet,after:incident.faultySnippet,subject:"manager-defined behavior",language:"custom"};return{version:1,generator:"team-studio-v1",candidate,template:{id:`custom:${id}`,version:1,name:incident.title,category:"external_dependency",difficulty:difficulty.toLowerCase() as "beginner"|"intermediate"|"advanced",summary:incident.signal,available:true,briefing:{title:incident.title,severity:difficulty==="ADVANCED"?"SEV-1":difficulty==="BEGINNER"?"SEV-3":"SEV-2",customerReport:incident.signal,initialAlert:incident.evidence[0]??incident.signal,knownImpact:[incident.objective],unaffectedSystems:["Original repository"]},intendedRootCause:incident.rootCause,hints:["Start with the production signal and evidence contract.",`Inspect ${incident.targetPath}.`,"Compare the failing behavior with the repository baseline.",incident.validationContract]},targetPath:incident.targetPath,baselineTarget:target.content,baselineHashes:Object.fromEntries(files.map(file=>[file.path,hash(file.content)])),testPaths:files.filter(file=>/(?:test|spec)/i.test(file.path)).map(file=>file.path),logs:incident.evidence,databaseEvidence:[incident.validationContract],healthEvidence:[`custom incident · ${incident.signal}`]}}

export function draftFromGitDiff(diff:string){const file=diff.match(/^\+\+\+ b\/(.+)$/m)?.[1]??"";const removed=[...diff.matchAll(/^-([^\-].*)$/gm)].map(m=>m[1]).join("\n").trim();const added=[...diff.matchAll(/^\+([^+].*)$/gm)].map(m=>m[1]).join("\n").trim();if(!file||!added||!removed)throw new TeamServiceError("DIFF_UNSUPPORTED","Paste a unified git diff with one clear source-file change.",422);return{title:`Regression in ${file.split("/").pop()}`,signal:"The previously fixed behavior has regressed in production.",rootCause:`The isolated copy reintroduces the pre-fix behavior in ${file}.`,targetPath:file,safeSnippet:added,faultySnippet:removed,evidence:[`ERROR regression observed in ${file}`,"Known-good behavior is present in the reviewed diff"],validationContract:`Restore the reviewed post-fix behavior in ${file} without unrelated changes.`,objective:"Diagnose the regression from evidence, repair it, and verify the known-good contract.",sourceType:"GIT_DIFF" as const,sourceRef:null};}
