import Link from "next/link";

export default function About() {
  return <main className="editorial-page">
    <section className="editorial-hero page-pad"><div><p className="eyebrow">ABOUT REPOREHEARSAL</p><h1>Production judgment is built through practice.</h1><p>RepoRehearsal turns a safe copy of real code into a focused incident: a signal to interpret, evidence to collect, a repair to make, and proof that the system recovered.</p><div className="actions"><Link className="button button-accent" href="/rehearsals/new">Try a live case →</Link><Link className="button button-ghost editorial-ghost" href="/repositories">Analyze a repository</Link></div></div><aside aria-label="The rehearsal loop"><span>THE REHEARSAL LOOP</span>{["Observe the signal", "Build an evidence trail", "Repair the smallest boundary", "Verify recovery", "Explain prevention"].map((step, index) => <div key={step}><i>{String(index + 1).padStart(2, "0")}</i><b>{step}</b></div>)}</aside></section>
    <section className="principle-section page-pad"><div className="section-heading"><div><p className="eyebrow">DESIGNED FOR SERIOUS PRACTICE</p><h2>Confidence without guesswork.</h2></div><p>The experience protects the productive tension of an incident while removing the risk of learning directly in production.</p></div><div className="principle-grid"><article><span>01</span><h3>The answer stays hidden</h3><p>Hints move from direction to principle. They do not paste in the repair, so the learner still has to reason.</p></article><article><span>02</span><h3>Evidence changes the score</h3><p>Logs inspected, hypotheses recorded, edits made, and checks run become measurable investigation signals.</p></article><article><span>03</span><h3>Validation is deterministic</h3><p>Known checks decide whether a repair is safe. The score rewards a working outcome and the path used to reach it.</p></article></div></section>
    <section className="about-system page-pad"><div><p className="eyebrow">FROM REPOSITORY TO REHEARSAL</p><h2>A bounded analysis engine, not a code-generating black box.</h2><p>The analyzer maps supported source and configuration files, detects a repairable boundary, and creates an incident around evidence that actually exists in the codebase.</p></div><div className="system-flow"><span>FILTERED SOURCE</span><i>→</i><span>CODE MAP</span><i>→</i><span>INCIDENT BRIEF</span><i>→</i><span>VERIFIED SCORE</span></div><ul><li>Original repositories remain untouched</li><li>Secrets, binaries, and generated folders are excluded</li><li>Uploaded code is not sent to OpenAI for report enhancement</li><li>Arbitrary shell execution and repository-controlled networking stay blocked</li></ul></section>
    <section className="editorial-cta page-pad"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Practice the part of engineering that tutorials skip.</h2><Link className="button button-dark" href="/rehearsals/new">Choose an incident →</Link></section>
  </main>;
}
