import Link from "next/link";
import type { Metadata } from "next";
import { getPublicRehearsalResult } from "../../../src/rehearsals/public-results";

export const dynamic="force-dynamic";
const origin="https://reporehersal.com";
function duration(seconds:number){return`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`}

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const{id}=await params;const result=await getPublicRehearsalResult(id);if(!result)return{title:"Verified result not found",robots:{index:false,follow:true}};const title=`${result.score}/100 · ${result.incidentName}`;const description=`Verified RepoRehearsal result on ${result.repositoryName}. Deterministic score, ${duration(result.durationSeconds)} completion time.`;return{title,description,robots:{index:true,follow:true},alternates:{canonical:`${origin}/verify/${id}`},openGraph:{title,description,type:"website",url:`${origin}/verify/${id}`,siteName:"RepoRehearsal",images:[{url:`${origin}/api/og/result?id=${encodeURIComponent(id)}`,width:1200,height:630,alt:title}]},twitter:{card:"summary_large_image",title,description,images:[`${origin}/api/og/result?id=${encodeURIComponent(id)}`]}}}

export default async function VerifiedResultPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const result=await getPublicRehearsalResult(id);if(!result)return <main className="not-found-page"><div><p className="not-found-code">VERIFY</p><h1>Verified result not found</h1><p>This result may not have been published, or the URL is incomplete.</p><div className="actions"><Link className="button button-dark" href="/">Back to home</Link><Link className="button button-ghost" href="/daily">Try today’s challenge</Link></div></div></main>;
  const url=`${origin}/verify/${result.id}`;const linkedIn=`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`;const badge=`[![RepoRehearsal verified: ${result.score}/100](${origin}/api/badges/result?score=${result.score})](${url})`;
  return <main className="verified-result-page rr-narrow"><header><div><span className="verified-mark">✓</span><div><p>Verified RepoRehearsal result</p><h1>{result.incidentName}</h1><span>Published from a deterministic rehearsal result. Score and validation details are server-stored and cannot be edited by the participant.</span></div></div><aside><strong>{result.score}</strong><span>/100</span></aside></header><section className="verified-meta"><div><span>Repository</span><b>{result.repositoryName}</b></div><div><span>Time</span><b>{duration(result.durationSeconds)}</b></div><div><span>Completed</span><b>{new Date(result.completedAt).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"})}</b></div><div><span>Verification ID</span><b>{result.id}</b></div></section><section className="verified-breakdown"><h2>Skill breakdown</h2>{result.validation.breakdown.map(item=><div key={item.label}><span>{item.label}</span><b>{item.earned}/{item.possible}</b><i><em style={{width:`${Math.max(0,Math.min(100,item.earned/item.possible*100))}%`}}/></i></div>)}</section><section className="verified-actions"><div><h2>Share this result</h2><p>Use the public URL on a portfolio or resume. The badge Markdown links back to this verification page.</p></div><a className="button button-dark" href={linkedIn} target="_blank" rel="noreferrer">Add to LinkedIn ↗</a><details><summary>Badge Markdown</summary><code>{badge}</code></details></section></main>}
