"use client";

import { useState } from "react";
import { usePlan } from "../components/PlanProvider";

export default function AccountManagement({ email }: { email: string }) {
  const { activePlan,ready,activate }=usePlan(); const [dialog,setDialog]=useState(false); const [confirmation,setConfirmation]=useState(""); const [status,setStatus]=useState("");
  function cancelMembership(){if(!window.confirm(`Cancel the ${activePlan === "TEAM" ? "Team" : "Pro"} membership and return to Free?`))return;activate("FREE");setStatus("Membership cancelled. Free access is now active.");}
  async function removeAccount(){setStatus("Deleting account…");const response=await fetch("/api/account",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation})});const body=await response.json();if(!response.ok){setStatus(body.error?.message??"The account could not be deleted.");return;}window.location.assign("/");}
  return <section className="account-management"><div><h2>Membership</h2><p>{ready?`${activePlan === "FREE" ? "Free" : activePlan === "PRO" ? "Pro" : "Team"} access is active.`:"Loading membership…"} Payments are not connected during preview.</p>{ready&&activePlan!=="FREE"&&<button className="button button-ghost" type="button" onClick={cancelMembership}>Cancel membership</button>}</div><div className="danger-zone"><h2>Delete account</h2><p>Permanently remove your profile, sessions, scores, team membership, and stored repository copies.</p><button className="button account-delete-button" type="button" onClick={()=>{setConfirmation("");setStatus("");setDialog(true)}}>Delete account</button></div>{status&&<p className="account-management-status" role="status">{status}</p>}{dialog&&<div className="confirmation-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setDialog(false)}}><div className="confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-account-title"><h2 id="delete-account-title">Delete your account?</h2><p>This cannot be undone. Enter <b>{email}</b> to verify the deletion.</p><label htmlFor="delete-account-confirmation">Account email</label><input id="delete-account-confirmation" type="email" autoFocus value={confirmation} onChange={event=>setConfirmation(event.target.value)} /><div><button className="button button-ghost" type="button" onClick={()=>setDialog(false)}>Keep account</button><button className="button account-delete-button" type="button" disabled={confirmation.toLowerCase()!==email.toLowerCase()||status==="Deleting account…"} onClick={removeAccount}>Delete permanently</button></div>{status&&<p role="alert">{status}</p>}</div></div>}</section>;
}
