"use client";

import { useEffect, useState } from "react";
type Summary = { configured: boolean; plan: "FREE" | "PRO" | "TEAM"; status: string; cancelAtPeriodEnd: boolean; currentPeriodEnd: string | null };

export default function AccountManagement({ email }: { email: string }) {
  const [summary,setSummary]=useState<Summary|null>(null); const [dialog,setDialog]=useState(false); const [confirmation,setConfirmation]=useState(""); const [status,setStatus]=useState(""); const [working,setWorking]=useState(false);
  const load=async()=>{const response=await fetch("/api/billing/subscription",{cache:"no-store"});if(response.ok)setSummary(await response.json())}; useEffect(()=>{void load()},[]);
  async function cancelMembership(){if(!window.confirm(`Cancel the ${summary?.plan === "TEAM" ? "Team" : "Pro"} membership at the end of its current period?`))return;setWorking(true);setStatus("");const response=await fetch("/api/billing/cancel",{method:"POST"});const body=await response.json();setWorking(false);if(!response.ok){setStatus(body.error?.message??"The membership could not be cancelled.");return;}setStatus("Cancellation is scheduled. Your paid access remains available until the end of the current billing period.");await load();}
  async function openPortal(){setWorking(true);setStatus("");const response=await fetch("/api/billing/portal",{method:"POST"});const body=await response.json();if(!response.ok||!body.url){setWorking(false);setStatus(body.error?.message??"The billing portal could not be opened.");return;}window.location.assign(body.url);}
  async function removeAccount(){setStatus("Deleting account…");const response=await fetch("/api/account",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation})});const body=await response.json();if(!response.ok){setStatus(body.error?.message??"The account could not be deleted.");return;}window.location.assign("/");}
  return <section className="account-management"><div><h2>Membership</h2><p>{!summary?"Loading membership…":summary.plan === "FREE"?"Free access is active.":`${summary.plan === "PRO" ? "Pro" : "Team"} access is ${summary.status === "trialing" ? "in its 7-day trial" : "active"}.`}</p>{summary?.plan!=="FREE"&&<div className="actions"><button className="button button-ghost" type="button" disabled={working} onClick={openPortal}>Manage payment details</button><button className="button button-ghost" type="button" disabled={working||summary.cancelAtPeriodEnd} onClick={cancelMembership}>{summary.cancelAtPeriodEnd?"Cancellation scheduled":"Cancel membership"}</button></div>}{summary?.cancelAtPeriodEnd&&summary.currentPeriodEnd&&<p className="account-management-status">Your membership ends on {new Date(summary.currentPeriodEnd).toLocaleDateString()}.</p>}</div><div className="danger-zone"><h2>Delete account</h2><p>Permanently remove your profile, sessions, scores, team membership, and stored repository copies.</p><button className="button account-delete-button" type="button" onClick={()=>{setConfirmation("");setStatus("");setDialog(true)}}>Delete account</button></div>{status&&<p className="account-management-status" role="status">{status}</p>}{dialog&&<div className="confirmation-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setDialog(false)}}><div className="confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-account-title"><h2 id="delete-account-title">Delete your account?</h2><p>This cannot be undone. Enter <b>{email}</b> to verify the deletion.</p><label htmlFor="delete-account-confirmation">Account email</label><input id="delete-account-confirmation" type="email" autoFocus value={confirmation} onChange={event=>setConfirmation(event.target.value)} /><div><button className="button button-ghost" type="button" onClick={()=>setDialog(false)}>Keep account</button><button className="button account-delete-button" type="button" disabled={confirmation.toLowerCase()!==email.toLowerCase()||status==="Deleting account…"} onClick={removeAccount}>Delete permanently</button></div>{status&&<p role="alert">{status}</p>}</div></div>}</section>;
}
