import Link from "next/link";

const steps = [
  ["I", "Map the repository", "Identify services, routes, migrations, tests, and reliability risks before selecting an exercise."],
  ["II", "Break an isolated copy", "Inject a deterministic fault only after the clean baseline passes. Your source stays untouched."],
  ["III", "Investigate & repair", "Use code, logs, tests, database evidence, and health checks. Then receive a scored report."],
];
const languages = ["TypeScript", "JavaScript", "Python", "Java", "C", "C++", "C#", "Go", "Rust", "Ruby", "PHP", "Kotlin", "Swift", "Scala"];

export default function Landing() {
  return <main className="home-page">
    <section className="home-hero rr-container"><div className="announcement-chip"><i />Isolated sandbox · your source is never modified</div><h1>Train on your repository. Not someone else's incidents.</h1><p>Curated scenario libraries teach you their bugs. RepoRehearsal turns your own codebase into a safe, scored incident, then grades the repair on evidence, not multiple choice.</p><div className="actions"><Link className="button button-blue" href="/rehearsals/new">Start a rehearsal</Link><Link className="button button-ghost" href="/repositories">Use your repository ↗</Link></div><small>No private repository or API key required.</small></section>
    <section className="briefing-wrap rr-container"><article className="incident-briefing"><header><div><span className="badge badge-red">SEV-2</span><b>Billing service</b></div><code>14:14 UTC</code></header><div className="briefing-body"><h3>New accounts cannot open billing</h3><p>HTTP 500 errors began shortly after a database migration. Existing customers appear unaffected.</p><div className="status-grid"><div className="status-tile degraded"><span>billing-api</span><b>Degraded</b></div><div className="status-tile healthy"><span>authentication</span><b>Healthy</b></div><div className="status-tile healthy"><span>dashboard</span><b>Healthy</b></div></div><pre><span>error</span>  GET /billing → 500   <i>request_id=req_8f2a</i></pre></div></article></section>
    <section className="steps-band"><div className="rr-container"><div className="center-heading"><h2>From repository to scored rehearsal</h2><p>The evidence-driven work between “something is broken” and “we know it is safe.”</p></div><div className="spec-card-grid">{steps.map(([number,title,copy]) => <article key={number}><span>{number}</span><h4>{title}</h4><p>{copy}</p></article>)}</div></div></section>
    <section className="failure-section rr-container"><div className="center-heading"><h2>Choose the kind of failure.</h2><p>Each case has a known root cause, observable evidence, a safe repair path, and deterministic validation.</p></div><div className="spec-card-grid"><article><code>DB</code><h4>Database migration</h4><p>Unsafe schema transitions, incomplete backfills, and mismatched record creation paths.</p></article><article><code>CFG</code><h4>Configuration failure</h4><p>Container host mismatches and environment-specific connection errors.</p></article><article><code>API</code><h4>External dependency</h4><p>Provider schema drift, partial responses, retry safety, and timeout handling.</p></article></div></section>
    <section className="language-section rr-container"><p>SUPPORTED LANGUAGES</p><div>{languages.map(language => <span key={language}>{language}</span>)}</div></section>
    <section className="compare-section rr-container"><div className="center-heading"><p className="eyebrow">WHY REPOREHEARSAL</p><h2>Realistic practice is common now. Practice on your own code isn't.</h2><p>Free scenario libraries and chat-based simulators both build real skill. Here's specifically where RepoRehearsal goes further.</p></div><div className="feature-table-scroll" style={{marginTop:"56px"}}><table className="feature-table"><thead><tr><th scope="col">Capability</th><th scope="col" className="selected">RepoRehearsal</th><th scope="col">Curated scenario libraries</th><th scope="col">Chat-based simulators</th></tr></thead><tbody><tr className="group-start"><th scope="row"><b>Practice on your own repository</b><span>Not just a fixed set of sample apps.</span></th><td className="selected"><span className="feature-check" aria-label="Included in RepoRehearsal">✓</span></td><td><span className="feature-value">Fixed scenarios only</span></td><td><span className="feature-value">Fixed scenarios only</span></td></tr><tr><th scope="row"><b>Deterministic grading with hidden checks</b><span>Catches a patched crash that leaves the root cause unfixed.</span></th><td className="selected"><span className="feature-check" aria-label="Included in RepoRehearsal">✓</span></td><td><span className="feature-value">Multiple choice</span></td><td><span className="feature-value">Facilitator-judged</span></td></tr><tr><th scope="row"><b>Real code, real logs, real database state</b><span>You read an actual stack trace, not a scripted prompt.</span></th><td className="selected"><span className="feature-check" aria-label="Included in RepoRehearsal">✓</span></td><td><span className="feature-check" aria-label="Included">✓</span></td><td><span className="feature-value">Simulated dialogue</span></td></tr><tr><th scope="row"><b>Team incident authoring from a real PR</b><span>Turn your own postmortem into training material.</span></th><td className="selected"><span className="feature-check" aria-label="Included in RepoRehearsal">✓</span></td><td><span className="feature-dash" aria-label="Not included">—</span></td><td><span className="feature-dash" aria-label="Not included">—</span></td></tr><tr><th scope="row"><b>Candidate debugging screens</b><span>One incident link, every applicant, comparable results.</span></th><td className="selected"><span className="feature-check" aria-label="Included in RepoRehearsal">✓</span></td><td><span className="feature-dash" aria-label="Not included">—</span></td><td><span className="feature-dash" aria-label="Not included">—</span></td></tr><tr><th scope="row"><b>Starting price</b><span>Free tier included either way.</span></th><td className="selected"><span className="feature-value">Free, Pro from $9.99/mo</span></td><td><span className="feature-value">Free</span></td><td><span className="feature-value">From ~$100+/mo per seat</span></td></tr></tbody></table></div></section>
    <section className="closing-cta rr-container"><h2>Your repository stays yours.</h2><p>Temporary copies. Redacted secrets. Allowlisted commands. Expiring workspaces.</p><p className="team-home-link">Training a team, or hiring? Turn your own incidents into practice. <Link className="text-link" href="/team/studio">See how →</Link></p><Link className="button button-dark" href="/rehearsals/new">Start a rehearsal</Link><Link className="text-link" href="/privacy">Security and privacy details →</Link></section>
  </main>;
}
