import Link from "next/link";

const steps = [
  ["01", "Map the repository", "We identify services, routes, migrations, tests, and reliability risks before selecting an exercise."],
  ["02", "Break an isolated copy", "A deterministic fault is injected only after the clean baseline passes. Your source stays untouched."],
  ["03", "Investigate, repair, learn", "Use code, logs, tests, database evidence, and health checks. Then receive a scored after-action report."],
];

export default function Landing() {
  return <main>
    <section className="hero page-pad">
      <div className="hero-copy"><p className="eyebrow"><span className="pulse"/> INCIDENT PRACTICE, WITHOUT THE INCIDENT</p><h1>Break it safely.<br/><em>Debug it seriously.</em></h1><p className="lede">RepoRehearsal turns a software repository into a realistic, isolated incident simulation—so developers can practice diagnosing production failures before production is at risk.</p><div className="actions"><Link className="button button-accent" href="/rehearsals/new">Start a rehearsal <span>→</span></Link><Link className="button button-ghost" href="/rehearsals/new?repositoryId=billing-demo">Configure demo incident</Link></div><p className="microcopy"><span>✓</span> No private repository required <span>✓</span> No API key required</p></div>
      <div className="incident-card" aria-label="Example incident report"><div className="window-bar"><span/><span/><span/><b>INCIDENT BRIEFING</b><i>LIVE</i></div><div className="incident-body"><div className="sev-row"><span className="badge badge-red">SEV-2</span><code>14:14:07 UTC</code></div><h2>New accounts cannot<br/>open billing</h2><p>HTTP 500 errors began shortly after a database migration. Existing customers appear unaffected.</p><div className="health-row"><span>billing-api</span><b className="bad">DEGRADED</b></div><div className="health-row"><span>authentication</span><b className="good">HEALTHY</b></div><div className="health-row"><span>dashboard</span><b className="good">HEALTHY</b></div><div className="log-line"><code>14:14:09</code><span>error</span><p>GET /billing → 500<br/><b>request_id=req_8f2a</b></p></div></div><div className="incident-footer"><span>YOUR OBJECTIVE</span><strong>Find the root cause. Repair it safely.</strong></div></div>
    </section>
    <section className="trust-strip"><span>BUILT FOR REAL ENGINEERING PRACTICE</span><b>TypeScript</b><b>Express</b><b>PostgreSQL</b><b>Prisma</b><b>Vitest</b><b>Docker</b></section>
    <section className="how page-pad"><p className="eyebrow">HOW IT WORKS</p><div className="section-heading"><h2>A complete incident loop.<br/><em>Not another coding challenge.</em></h2><p>Practice the messy, evidence-driven work between “something is broken” and “we know it is safe.”</p></div><div className="steps">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><div className="step-icon">{n === "01" ? "⌗" : n === "02" ? "⚡" : "✓"}</div><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="incident-types page-pad"><div><p className="eyebrow">CONTROLLED. REPEATABLE. REALISTIC.</p><h2>Three ways<br/>things go wrong.</h2><p>Every template has a known root cause, observable evidence, safe repair path, and deterministic validation.</p></div><div className="type-list"><article><span>DB</span><div><b>Database migration</b><p>Unsafe schema transitions, incomplete backfills, and mismatched record creation paths.</p></div><i>AVAILABLE</i></article><article><span>CFG</span><div><b>Configuration failure</b><p>Container host mismatches and environment-specific connection errors.</p></div><i>AVAILABLE</i></article><article><span>API</span><div><b>External dependency</b><p>Provider schema drift, partial responses, and timeout handling.</p></div><i>AVAILABLE</i></article></div></section>
    <section className="privacy-band"><p className="eyebrow">A SAFE PLACE TO FAIL</p><h2>Your repository stays yours.</h2><p>Every exercise runs against a temporary copy. Secrets are redacted, commands are allowlisted, workspaces expire, and the original repository is never modified.</p><Link className="text-link" href="/privacy">Read our security & privacy approach →</Link></section>
  </main>;
}
