import { NextResponse } from "next/server";
import { z } from "zod";
import { getAuthenticatedUser } from "../../../auth";
import { deleteCustomIncident, draftFromGitDiff, listCustomIncidents, saveCustomIncident, updateCustomIncidentStatus } from "../../../../src/incidents/custom-incidents";
import { TeamServiceError } from "../../../../src/team/team-service";
import { draftFromIncidentExport } from "../../../../src/incidents/importers";

const base=z.object({repositoryId:z.string().min(1).max(100),title:z.string().min(4).max(140),signal:z.string().min(10).max(1000),rootCause:z.string().min(10).max(1500),targetPath:z.string().min(1).max(500),safeSnippet:z.string().min(1).max(30000),faultySnippet:z.string().min(1).max(30000),evidence:z.array(z.string().min(3).max(1000)).min(1).max(12),validationContract:z.string().min(10).max(1500),objective:z.string().min(10).max(1000),sourceType:z.enum(["MANUAL","GIT_DIFF","PAGERDUTY","DATADOG","JIRA"]),sourceRef:z.string().max(500).nullable()});
const action=z.discriminatedUnion("action",[z.object({action:z.literal("save"),incident:base}),z.object({action:z.literal("publish"),id:z.string().uuid()}),z.object({action:z.literal("unpublish"),id:z.string().uuid()}),z.object({action:z.literal("delete"),id:z.string().uuid()}),z.object({action:z.literal("draft-from-diff"),diff:z.string().min(20).max(200000)}),z.object({action:z.literal("draft-from-tool"),provider:z.enum(["PAGERDUTY","DATADOG","JIRA"]),payload:z.string().min(2).max(200000)})]);
function fail(error:unknown){if(error instanceof TeamServiceError)return NextResponse.json({error:{code:error.code,message:error.message}},{status:error.status});console.error("Custom incident API",error);return NextResponse.json({error:{code:"INCIDENT_STUDIO_UNAVAILABLE",message:"The incident studio is temporarily unavailable."}},{status:500})}
export async function GET(){const user=await getAuthenticatedUser();if(!user)return NextResponse.json({error:{code:"AUTHENTICATION_REQUIRED",message:"Sign in to open your team's incident library."}},{status:401});try{return NextResponse.json({incidents:await listCustomIncidents(user)})}catch(error){return fail(error)}}
export async function POST(request:Request){const user=await getAuthenticatedUser();if(!user)return NextResponse.json({error:{code:"AUTHENTICATION_REQUIRED",message:"Sign in to author a custom incident."}},{status:401});const parsed=action.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:{code:"INVALID_INCIDENT",message:"Review the incident contract and try again."}},{status:400});try{if(parsed.data.action==="draft-from-diff")return NextResponse.json({draft:draftFromGitDiff(parsed.data.diff)});if(parsed.data.action==="draft-from-tool")return NextResponse.json({draft:draftFromIncidentExport(parsed.data.provider,parsed.data.payload)});if(parsed.data.action==="save")return NextResponse.json({incident:await saveCustomIncident(user,parsed.data.incident)},{status:201});if(parsed.data.action==="delete")return NextResponse.json(await deleteCustomIncident(user,parsed.data.id));return NextResponse.json({incident:await updateCustomIncidentStatus(user,parsed.data.id,parsed.data.action==="publish"?"PUBLISHED":"DRAFT")})}catch(error){return fail(error)}}
