export type CuratedRepository = {
  id: string;
  name: string;
  fullName: string;
  url: string;
  description: string;
  stars: number;
  sizeKb: number;
  license: string;
  category: "Full-stack" | "Backend" | "Data" | "Applications" | "Frontend" | "Developer tooling";
  focus: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
};

// Snapshot curated from GitHub's public repository index on 2026-07-16.
// Eligibility: active, non-fork TypeScript projects with recognized open-source licenses and bounded repository size.
export const curatedRepositories = [
  {
    "id": "curated-001",
    "name": "toon",
    "fullName": "toon-format/toon",
    "url": "https://github.com/toon-format/toon",
    "description": "🎒 Token-Oriented Object Notation (TOON) – Compact, human-readable, schema-aware JSON for LLM prompts. Spec, benchmarks, TypeScript SDK.",
    "stars": 24880,
    "sizeKb": 2252,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-002",
    "name": "devtools-v6",
    "fullName": "vuejs/devtools-v6",
    "url": "https://github.com/vuejs/devtools-v6",
    "description": "⚙️ Browser devtools extension for debugging Vue.js applications.",
    "stars": 24713,
    "sizeKb": 14716,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-003",
    "name": "github-profile-readme-generator",
    "fullName": "rahuldkjain/github-profile-readme-generator",
    "url": "https://github.com/rahuldkjain/github-profile-readme-generator",
    "description": "🚀 Generate GitHub profile README easily with the latest add-ons like visitors count, GitHub stats, etc using minimal UI.",
    "stars": 24353,
    "sizeKb": 18580,
    "license": "Apache-2.0",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-004",
    "name": "electron-react-boilerplate",
    "fullName": "electron-react-boilerplate/electron-react-boilerplate",
    "url": "https://github.com/electron-react-boilerplate/electron-react-boilerplate",
    "description": "A Foundation for Scalable Cross-Platform Apps",
    "stars": 24253,
    "sizeKb": 17503,
    "license": "MIT",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-005",
    "name": "dockge",
    "fullName": "louislam/dockge",
    "url": "https://github.com/louislam/dockge",
    "description": "A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager",
    "stars": 23801,
    "sizeKb": 1270,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-006",
    "name": "yup",
    "fullName": "jquense/yup",
    "url": "https://github.com/jquense/yup",
    "description": "Dead simple Object schema validation",
    "stars": 23673,
    "sizeKb": 4340,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-007",
    "name": "react-redux",
    "fullName": "reduxjs/react-redux",
    "url": "https://github.com/reduxjs/react-redux",
    "description": "Official React bindings for Redux",
    "stars": 23468,
    "sizeKb": 11837,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-008",
    "name": "github1s",
    "fullName": "conwnet/github1s",
    "url": "https://github.com/conwnet/github1s",
    "description": "One second to read GitHub code with VS Code.",
    "stars": 23297,
    "sizeKb": 18877,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-009",
    "name": "agents.md",
    "fullName": "agentsmd/agents.md",
    "url": "https://github.com/agentsmd/agents.md",
    "description": "AGENTS.md — a simple, open format for guiding coding agents",
    "stars": 23055,
    "sizeKb": 1912,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-010",
    "name": "ai-job-search",
    "fullName": "MadsLorentzen/ai-job-search",
    "url": "https://github.com/MadsLorentzen/ai-job-search",
    "description": "The job search that runs on your machine. AI job application framework built on Claude Code: evaluate postings, tailor CVs, write cover letters, prep interviews. Fork it and own it",
    "stars": 23052,
    "sizeKb": 3004,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-011",
    "name": "wechaty",
    "fullName": "wechaty/wechaty",
    "url": "https://github.com/wechaty/wechaty",
    "description": "Conversational RPA SDK for Chatbot Makers. Join our Discord: https://discord.gg/7q8NBZbQzt",
    "stars": 22913,
    "sizeKb": 9027,
    "license": "Apache-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-012",
    "name": "react-grid-layout",
    "fullName": "react-grid-layout/react-grid-layout",
    "url": "https://github.com/react-grid-layout/react-grid-layout",
    "description": "A draggable and resizable grid layout with responsive breakpoints, for React.",
    "stars": 22350,
    "sizeKb": 17598,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-013",
    "name": "vueuse",
    "fullName": "vueuse/vueuse",
    "url": "https://github.com/vueuse/vueuse",
    "description": "Collection of essential Vue Composition Utilities for Vue 3",
    "stars": 22305,
    "sizeKb": 16768,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-014",
    "name": "gpt-crawler",
    "fullName": "BuilderIO/gpt-crawler",
    "url": "https://github.com/BuilderIO/gpt-crawler",
    "description": "Crawl a site to generate knowledge files to create your own custom GPT from a URL",
    "stars": 22259,
    "sizeKb": 884,
    "license": "ISC",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-015",
    "name": "opcode",
    "fullName": "winfunc/opcode",
    "url": "https://github.com/winfunc/opcode",
    "description": "A powerful GUI app and Toolkit for Claude Code - Create custom agents, manage interactive Claude Code sessions, run secure background agents, and more.",
    "stars": 22177,
    "sizeKb": 2570,
    "license": "AGPL-3.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-016",
    "name": "winboat",
    "fullName": "TibixDev/winboat",
    "url": "https://github.com/TibixDev/winboat",
    "description": "Run Windows apps on 🐧 Linux with ✨ seamless integration",
    "stars": 21954,
    "sizeKb": 16981,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-017",
    "name": "jotai",
    "fullName": "pmndrs/jotai",
    "url": "https://github.com/pmndrs/jotai",
    "description": "👻 Primitive and flexible state management for React",
    "stars": 21224,
    "sizeKb": 15190,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-018",
    "name": "deskreen",
    "fullName": "pavlobu/deskreen",
    "url": "https://github.com/pavlobu/deskreen",
    "description": "Deskreen turns any device with a web browser into a secondary screen for your computer. ⭐️ Star to support our work!",
    "stars": 21148,
    "sizeKb": 11258,
    "license": "AGPL-3.0",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-019",
    "name": "ralph",
    "fullName": "snarktank/ralph",
    "url": "https://github.com/snarktank/ralph",
    "description": "Ralph is an autonomous AI agent loop that runs repeatedly until all PRD items are complete.",
    "stars": 21090,
    "sizeKb": 4705,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-020",
    "name": "docmost",
    "fullName": "docmost/docmost",
    "url": "https://github.com/docmost/docmost",
    "description": "Docmost is an open-source collaborative wiki and documentation software. It is an open-source alternative to Confluence and Notion.",
    "stars": 21020,
    "sizeKb": 14029,
    "license": "AGPL-3.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-021",
    "name": "newsnow",
    "fullName": "ourongxing/newsnow",
    "url": "https://github.com/ourongxing/newsnow",
    "description": "Elegant reading of real-time and hottest news",
    "stars": 21017,
    "sizeKb": 5998,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-022",
    "name": "visx",
    "fullName": "airbnb/visx",
    "url": "https://github.com/airbnb/visx",
    "description": "🐯 visx | visualization components",
    "stars": 20960,
    "sizeKb": 16763,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-023",
    "name": "rrweb",
    "fullName": "rrweb-io/rrweb",
    "url": "https://github.com/rrweb-io/rrweb",
    "description": "record and replay the web",
    "stars": 19879,
    "sizeKb": 12629,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-024",
    "name": "qinglong",
    "fullName": "whyour/qinglong",
    "url": "https://github.com/whyour/qinglong",
    "description": "支持 Python3、JavaScript、Shell、Typescript 的定时任务管理平台（Timed task management platform supporting Python3, JavaScript, Shell, Typescript）",
    "stars": 19697,
    "sizeKb": 7830,
    "license": "Apache-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-025",
    "name": "taxonomy",
    "fullName": "shadcn-ui/taxonomy",
    "url": "https://github.com/shadcn-ui/taxonomy",
    "description": "An open source application built using the new router, server components and everything new in Next.js 13.",
    "stars": 19267,
    "sizeKb": 14600,
    "license": "MIT",
    "category": "Full-stack",
    "focus": "Integration boundaries",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-026",
    "name": "core",
    "fullName": "adonisjs/core",
    "url": "https://github.com/adonisjs/core",
    "description": "AdonisJS is a TypeScript-first web framework for building web apps and API servers. It comes with support for testing, modern tooling, an ecosystem of official packages, and more.",
    "stars": 19040,
    "sizeKb": 6404,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-027",
    "name": "reselect",
    "fullName": "reduxjs/reselect",
    "url": "https://github.com/reduxjs/reselect",
    "description": "Selector library for Redux",
    "stars": 19029,
    "sizeKb": 6109,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-028",
    "name": "motion-canvas",
    "fullName": "motion-canvas/motion-canvas",
    "url": "https://github.com/motion-canvas/motion-canvas",
    "description": "Visualize Your Ideas With Code",
    "stars": 18798,
    "sizeKb": 11047,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-029",
    "name": "wangEditor",
    "fullName": "wangeditor-team/wangEditor",
    "url": "https://github.com/wangeditor-team/wangEditor",
    "description": "wangEditor, open-source Web rich text editor 开源 Web 富文本编辑器",
    "stars": 18362,
    "sizeKb": 19165,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-030",
    "name": "msw",
    "fullName": "mswjs/msw",
    "url": "https://github.com/mswjs/msw",
    "description": "Industry standard API mocking for JavaScript.",
    "stars": 18073,
    "sizeKb": 14237,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-031",
    "name": "vitepress",
    "fullName": "vuejs/vitepress",
    "url": "https://github.com/vuejs/vitepress",
    "description": "Vite & Vue powered static site generator.",
    "stars": 18019,
    "sizeKb": 16348,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-032",
    "name": "CopyTranslator",
    "fullName": "CopyTranslator/CopyTranslator",
    "url": "https://github.com/CopyTranslator/CopyTranslator",
    "description": "🔠Foreign language reading and translation assistant based on copy and translate.",
    "stars": 17975,
    "sizeKb": 10964,
    "license": "GPL-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-033",
    "name": "redux-thunk",
    "fullName": "reduxjs/redux-thunk",
    "url": "https://github.com/reduxjs/redux-thunk",
    "description": "Thunk middleware for Redux",
    "stars": 17692,
    "sizeKb": 3427,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-034",
    "name": "lx-music-mobile",
    "fullName": "lyswhut/lx-music-mobile",
    "url": "https://github.com/lyswhut/lx-music-mobile",
    "description": "一个基于 React native 开发的音乐软件",
    "stars": 17504,
    "sizeKb": 11460,
    "license": "Apache-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-035",
    "name": "dnd-kit",
    "fullName": "clauderic/dnd-kit",
    "url": "https://github.com/clauderic/dnd-kit",
    "description": "The modern toolkit for building drag and drop interfaces",
    "stars": 17412,
    "sizeKb": 11750,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-036",
    "name": "type-fest",
    "fullName": "sindresorhus/type-fest",
    "url": "https://github.com/sindresorhus/type-fest",
    "description": "A collection of essential TypeScript types",
    "stars": 17300,
    "sizeKb": 3109,
    "license": "CC0-1.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-037",
    "name": "ConvertX",
    "fullName": "C4illin/ConvertX",
    "url": "https://github.com/C4illin/ConvertX",
    "description": "💾 Self-hosted online file converter. Supports 1000+ formats ⚙️",
    "stars": 17226,
    "sizeKb": 2376,
    "license": "AGPL-3.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-038",
    "name": "react-window",
    "fullName": "bvaughn/react-window",
    "url": "https://github.com/bvaughn/react-window",
    "description": "React components for efficiently rendering large lists and tabular data",
    "stars": 17194,
    "sizeKb": 8979,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-039",
    "name": "ky",
    "fullName": "sindresorhus/ky",
    "url": "https://github.com/sindresorhus/ky",
    "description": "🌳 Tiny & elegant JavaScript HTTP client based on the Fetch API",
    "stars": 16988,
    "sizeKb": 1444,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-040",
    "name": "gitmoji",
    "fullName": "carloscuesta/gitmoji",
    "url": "https://github.com/carloscuesta/gitmoji",
    "description": "An emoji guide for your commit messages. 😜",
    "stars": 16787,
    "sizeKb": 7983,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-041",
    "name": "maxun",
    "fullName": "getmaxun/maxun",
    "url": "https://github.com/getmaxun/maxun",
    "description": "🔥 The open-source no-code platform for web scraping, crawling, search and AI data extraction • Turn websites into structured APIs in minutes 🔥",
    "stars": 16518,
    "sizeKb": 7159,
    "license": "AGPL-3.0",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-042",
    "name": "better-scroll",
    "fullName": "ustbhuangyi/better-scroll",
    "url": "https://github.com/ustbhuangyi/better-scroll",
    "description": ":scroll: inspired by iscroll, and it supports more features and has a better scroll perfermance",
    "stars": 16483,
    "sizeKb": 18682,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-043",
    "name": "flatpickr",
    "fullName": "flatpickr/flatpickr",
    "url": "https://github.com/flatpickr/flatpickr",
    "description": "lightweight, powerful javascript datetimepicker with no dependencies",
    "stars": 16466,
    "sizeKb": 7848,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-044",
    "name": "bolt.new",
    "fullName": "stackblitz/bolt.new",
    "url": "https://github.com/stackblitz/bolt.new",
    "description": "Prompt, run, edit, and deploy full-stack web applications. -- bolt.new -- Help Center: https://support.bolt.new/ -- Community Support: https://discord.com/invite/stackblitz",
    "stars": 16461,
    "sizeKb": 1072,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-045",
    "name": "tremor-npm",
    "fullName": "tremorlabs/tremor-npm",
    "url": "https://github.com/tremorlabs/tremor-npm",
    "description": "React components to build charts and dashboards",
    "stars": 16460,
    "sizeKb": 11495,
    "license": "Apache-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-046",
    "name": "freellmapi",
    "fullName": "tashfeenahmed/freellmapi",
    "url": "https://github.com/tashfeenahmed/freellmapi",
    "description": "OpenAI-compatible proxy that stacks the free tiers of 28 LLM providers (~4B tokens/month) behind one /v1 endpoint — plus any custom OpenAI-compatible endpoint. Smart routing, autom",
    "stars": 16196,
    "sizeKb": 4074,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-047",
    "name": "react-native-maps",
    "fullName": "react-native-maps/react-native-maps",
    "url": "https://github.com/react-native-maps/react-native-maps",
    "description": "React Native Mapview component for iOS + Android",
    "stars": 15979,
    "sizeKb": 14276,
    "license": "MIT",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-048",
    "name": "gitdiagram",
    "fullName": "ahmedkhaleel2004/gitdiagram",
    "url": "https://github.com/ahmedkhaleel2004/gitdiagram",
    "description": "Free, simple, fast interactive diagrams for any GitHub repository",
    "stars": 15815,
    "sizeKb": 1794,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-049",
    "name": "json-render",
    "fullName": "vercel-labs/json-render",
    "url": "https://github.com/vercel-labs/json-render",
    "description": "The Generative UI framework",
    "stars": 15701,
    "sizeKb": 6083,
    "license": "Apache-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-050",
    "name": "Figma-Context-MCP",
    "fullName": "GLips/Figma-Context-MCP",
    "url": "https://github.com/GLips/Figma-Context-MCP",
    "description": "MCP server to provide Figma layout information to AI coding agents like Cursor",
    "stars": 15413,
    "sizeKb": 1189,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-051",
    "name": "sass",
    "fullName": "sass/sass",
    "url": "https://github.com/sass/sass",
    "description": "Sass makes CSS fun!",
    "stars": 15372,
    "sizeKb": 2276,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-052",
    "name": "ioredis",
    "fullName": "redis/ioredis",
    "url": "https://github.com/redis/ioredis",
    "description": "🚀 A robust, performance-focused, and full-featured Redis client for Node.js.",
    "stars": 15309,
    "sizeKb": 8305,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-053",
    "name": "uuid",
    "fullName": "uuidjs/uuid",
    "url": "https://github.com/uuidjs/uuid",
    "description": "Generate RFC-compliant UUIDs in JavaScript",
    "stars": 15303,
    "sizeKb": 4239,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-054",
    "name": "ts-pattern",
    "fullName": "gvergnaud/ts-pattern",
    "url": "https://github.com/gvergnaud/ts-pattern",
    "description": "🎨 The exhaustive Pattern Matching library for TypeScript, with smart type inference.",
    "stars": 15081,
    "sizeKb": 2754,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-055",
    "name": "hooks",
    "fullName": "alibaba/hooks",
    "url": "https://github.com/alibaba/hooks",
    "description": "A high-quality & reliable React Hooks library. https://alibaba.github.io/hooks/",
    "stars": 14965,
    "sizeKb": 13515,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-056",
    "name": "ScrollMagic",
    "fullName": "janpaepke/ScrollMagic",
    "url": "https://github.com/janpaepke/ScrollMagic",
    "description": "The javascript library for magical scroll interactions.",
    "stars": 14948,
    "sizeKb": 5889,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-057",
    "name": "got",
    "fullName": "sindresorhus/got",
    "url": "https://github.com/sindresorhus/got",
    "description": "🌐 Human-friendly and powerful HTTP request library for Node.js",
    "stars": 14924,
    "sizeKb": 3913,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-058",
    "name": "react-sketchapp",
    "fullName": "airbnb/react-sketchapp",
    "url": "https://github.com/airbnb/react-sketchapp",
    "description": "render React components to Sketch ⚛️💎",
    "stars": 14877,
    "sizeKb": 4428,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-059",
    "name": "domain-driven-hexagon",
    "fullName": "Sairyss/domain-driven-hexagon",
    "url": "https://github.com/Sairyss/domain-driven-hexagon",
    "description": "Learn Domain-Driven Design, software architecture, design patterns, best practices. Code examples included",
    "stars": 14786,
    "sizeKb": 7445,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-060",
    "name": "pinia",
    "fullName": "vuejs/pinia",
    "url": "https://github.com/vuejs/pinia",
    "description": "🍍 Intuitive, type safe, light and flexible Store for Vue using the composition api with DevTools support",
    "stars": 14662,
    "sizeKb": 10454,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-061",
    "name": "soybean-admin",
    "fullName": "soybeanjs/soybean-admin",
    "url": "https://github.com/soybeanjs/soybean-admin",
    "description": "A clean, elegant, beautiful and powerful admin template, based on Vue3, Vite7, TypeScript, Pinia, NaiveUI and UnoCSS. 一个清新优雅、高颜值且功能强大的后台管理模板，基于最新的前端技术栈，包括 Vue3, Vite8, TypeScript, ",
    "stars": 14625,
    "sizeKb": 16926,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-062",
    "name": "lenis",
    "fullName": "darkroomengineering/lenis",
    "url": "https://github.com/darkroomengineering/lenis",
    "description": "Smooth scroll as it should be",
    "stars": 14382,
    "sizeKb": 10020,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-063",
    "name": "drawnix",
    "fullName": "plait-board/drawnix",
    "url": "https://github.com/plait-board/drawnix",
    "description": "开源白板工具（SaaS），一体化白板，包含思维导图、流程图、自由画等。All in one open-source whiteboard tool with mind, flowchart, freehand and etc.",
    "stars": 14275,
    "sizeKb": 1957,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-064",
    "name": "commerce",
    "fullName": "vercel/commerce",
    "url": "https://github.com/vercel/commerce",
    "description": "Next.js Commerce",
    "stars": 14149,
    "sizeKb": 11109,
    "license": "MIT",
    "category": "Full-stack",
    "focus": "Integration boundaries",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-065",
    "name": "claudian",
    "fullName": "YishenTu/claudian",
    "url": "https://github.com/YishenTu/claudian",
    "description": "An Obsidian plugin that embeds Claude Code/Codex as an AI collaborator in your vault",
    "stars": 14098,
    "sizeKb": 9407,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-066",
    "name": "pretty-ts-errors",
    "fullName": "yoavbls/pretty-ts-errors",
    "url": "https://github.com/yoavbls/pretty-ts-errors",
    "description": "🔵 Make TypeScript errors prettier and human-readable in VSCode 🎀",
    "stars": 14077,
    "sizeKb": 6772,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-067",
    "name": "react-content-loader",
    "fullName": "danilowoz/react-content-loader",
    "url": "https://github.com/danilowoz/react-content-loader",
    "description": "⚪ SVG-Powered component to easily create skeleton loadings.",
    "stars": 13997,
    "sizeKb": 6630,
    "license": "MIT",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-068",
    "name": "cropperjs",
    "fullName": "fengyuanchen/cropperjs",
    "url": "https://github.com/fengyuanchen/cropperjs",
    "description": "JavaScript image cropper.",
    "stars": 13856,
    "sizeKb": 16014,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-069",
    "name": "OpenStock",
    "fullName": "Open-Dev-Society/OpenStock",
    "url": "https://github.com/Open-Dev-Society/OpenStock",
    "description": "OpenStock is an open-source alternative to expensive market platforms. Track real-time prices, set personalized alerts, and explore detailed company insights — built openly, for ev",
    "stars": 13837,
    "sizeKb": 2286,
    "license": "AGPL-3.0",
    "category": "Full-stack",
    "focus": "Integration boundaries",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-070",
    "name": "Vencord",
    "fullName": "Vendicated/Vencord",
    "url": "https://github.com/Vendicated/Vencord",
    "description": "The cutest Discord modification",
    "stars": 13722,
    "sizeKb": 12333,
    "license": "GPL-3.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-071",
    "name": "satori",
    "fullName": "vercel/satori",
    "url": "https://github.com/vercel/satori",
    "description": "Enlightened library to convert HTML and CSS to SVG",
    "stars": 13656,
    "sizeKb": 7650,
    "license": "MPL-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-072",
    "name": "color-thief",
    "fullName": "lokesh/color-thief",
    "url": "https://github.com/lokesh/color-thief",
    "description": "Grab the color palette from an image using just Javascript. Works in the browser and in Node.",
    "stars": 13599,
    "sizeKb": 3439,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-073",
    "name": "draw-a-ui",
    "fullName": "SawyerHood/draw-a-ui",
    "url": "https://github.com/SawyerHood/draw-a-ui",
    "description": "Draw a mockup and generate html for it",
    "stars": 13584,
    "sizeKb": 999,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-074",
    "name": "shiki",
    "fullName": "shikijs/shiki",
    "url": "https://github.com/shikijs/shiki",
    "description": "A beautiful yet powerful syntax highlighter",
    "stars": 13542,
    "sizeKb": 16572,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-075",
    "name": "nanobrowser",
    "fullName": "nanobrowser/nanobrowser",
    "url": "https://github.com/nanobrowser/nanobrowser",
    "description": "Open-Source Chrome extension for AI-powered web automation. Run multi-agent workflows using your own LLM API key. Alternative to OpenAI Operator.",
    "stars": 13473,
    "sizeKb": 1151,
    "license": "Apache-2.0",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-076",
    "name": "SponsorBlock",
    "fullName": "ajayyy/SponsorBlock",
    "url": "https://github.com/ajayyy/SponsorBlock",
    "description": "Skip YouTube video sponsors (browser extension)",
    "stars": 13451,
    "sizeKb": 17206,
    "license": "GPL-3.0",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-077",
    "name": "react-toastify",
    "fullName": "fkhadra/react-toastify",
    "url": "https://github.com/fkhadra/react-toastify",
    "description": "React notification made easy 🚀 !",
    "stars": 13435,
    "sizeKb": 16655,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-078",
    "name": "ui-router",
    "fullName": "angular-ui/ui-router",
    "url": "https://github.com/angular-ui/ui-router",
    "description": "The de-facto solution to flexible routing with nested views in AngularJS",
    "stars": 13431,
    "sizeKb": 13457,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-079",
    "name": "chartist",
    "fullName": "chartist-js/chartist",
    "url": "https://github.com/chartist-js/chartist",
    "description": "Simple responsive charts",
    "stars": 13392,
    "sizeKb": 15528,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-080",
    "name": "peerjs",
    "fullName": "peers/peerjs",
    "url": "https://github.com/peers/peerjs",
    "description": "Simple peer-to-peer with WebRTC.",
    "stars": 13391,
    "sizeKb": 11022,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-081",
    "name": "react-redux-typescript-guide",
    "fullName": "piotrwitek/react-redux-typescript-guide",
    "url": "https://github.com/piotrwitek/react-redux-typescript-guide",
    "description": "The complete guide to static typing in \"React & Redux\" apps using TypeScript",
    "stars": 13279,
    "sizeKb": 2743,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-082",
    "name": "ext-saladict",
    "fullName": "crimx/ext-saladict",
    "url": "https://github.com/crimx/ext-saladict",
    "description": "🥗 All-in-one professional pop-up dictionary and page translator which supports multiple search modes, page translations, new word notebook and PDF selection searching.",
    "stars": 13206,
    "sizeKb": 16352,
    "license": "MIT",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-083",
    "name": "ts-node",
    "fullName": "TypeStrong/ts-node",
    "url": "https://github.com/TypeStrong/ts-node",
    "description": "TypeScript execution and REPL for node.js",
    "stars": 13134,
    "sizeKb": 8254,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-084",
    "name": "plasmo",
    "fullName": "PlasmoHQ/plasmo",
    "url": "https://github.com/PlasmoHQ/plasmo",
    "description": "🧩 The Browser Extension Framework",
    "stars": 13107,
    "sizeKb": 6467,
    "license": "MIT",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-085",
    "name": "stimulus",
    "fullName": "hotwired/stimulus",
    "url": "https://github.com/hotwired/stimulus",
    "description": "A modest JavaScript framework for the HTML you already have",
    "stars": 13071,
    "sizeKb": 4593,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-086",
    "name": "google-webfonts-helper",
    "fullName": "majodev/google-webfonts-helper",
    "url": "https://github.com/majodev/google-webfonts-helper",
    "description": "A Hassle-Free Way to Self-Host Google Fonts. Get eot, ttf, svg, woff and woff2 files + CSS snippets",
    "stars": 13025,
    "sizeKb": 792,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-087",
    "name": "puck",
    "fullName": "puckeditor/puck",
    "url": "https://github.com/puckeditor/puck",
    "description": "The visual editor for React.",
    "stars": 12970,
    "sizeKb": 5888,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-088",
    "name": "redux-persist",
    "fullName": "rt2zz/redux-persist",
    "url": "https://github.com/rt2zz/redux-persist",
    "description": "persist and rehydrate a redux store",
    "stars": 12967,
    "sizeKb": 1111,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-089",
    "name": "playground",
    "fullName": "tensorflow/playground",
    "url": "https://github.com/tensorflow/playground",
    "description": "Play with neural networks!",
    "stars": 12966,
    "sizeKb": 1454,
    "license": "Apache-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-090",
    "name": "markmap",
    "fullName": "markmap/markmap",
    "url": "https://github.com/markmap/markmap",
    "description": "Build mindmaps with plain text",
    "stars": 12965,
    "sizeKb": 1788,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-091",
    "name": "cmdk",
    "fullName": "dip/cmdk",
    "url": "https://github.com/dip/cmdk",
    "description": "Fast, unstyled command menu React component.",
    "stars": 12804,
    "sizeKb": 798,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-092",
    "name": "comlink",
    "fullName": "GoogleChromeLabs/comlink",
    "url": "https://github.com/GoogleChromeLabs/comlink",
    "description": "Comlink makes WebWorkers enjoyable.",
    "stars": 12747,
    "sizeKb": 2152,
    "license": "Apache-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-093",
    "name": "claudecodeui",
    "fullName": "siteboon/claudecodeui",
    "url": "https://github.com/siteboon/claudecodeui",
    "description": "Use Claude Code, OpenCode, Cursor CLI, and Codex on mobile and web with CloudCLI (aka Claude Code UI). CloudCLI is a free open source webui/GUI that helps you manage your Claude Co",
    "stars": 12667,
    "sizeKb": 11867,
    "license": "AGPL-3.0",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-094",
    "name": "sonner",
    "fullName": "emilkowalski/sonner",
    "url": "https://github.com/emilkowalski/sonner",
    "description": "An opinionated toast component for React.",
    "stars": 12650,
    "sizeKb": 1224,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-095",
    "name": "shadcn-admin",
    "fullName": "satnaing/shadcn-admin",
    "url": "https://github.com/satnaing/shadcn-admin",
    "description": "Admin Dashboard UI built with Shadcn and Vite.",
    "stars": 12635,
    "sizeKb": 3313,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-096",
    "name": "snabbdom",
    "fullName": "snabbdom/snabbdom",
    "url": "https://github.com/snabbdom/snabbdom",
    "description": "A virtual DOM library with focus on simplicity, modularity, powerful features and performance.",
    "stars": 12387,
    "sizeKb": 4997,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-097",
    "name": "boardgame.io",
    "fullName": "boardgameio/boardgame.io",
    "url": "https://github.com/boardgameio/boardgame.io",
    "description": "State Management and Multiplayer Networking for Turn-Based Games",
    "stars": 12374,
    "sizeKb": 13570,
    "license": "MIT",
    "category": "Applications",
    "focus": "Runtime integrations",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-098",
    "name": "note-gen",
    "fullName": "codexu/note-gen",
    "url": "https://github.com/codexu/note-gen",
    "description": "A cross-platform Markdown AI note-taking software.",
    "stars": 12302,
    "sizeKb": 14896,
    "license": "GPL-3.0",
    "category": "Full-stack",
    "focus": "Integration boundaries",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-099",
    "name": "chokidar",
    "fullName": "paulmillr/chokidar",
    "url": "https://github.com/paulmillr/chokidar",
    "description": "Minimal and efficient cross-platform file watching library",
    "stars": 12176,
    "sizeKb": 2113,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-100",
    "name": "claude-context",
    "fullName": "zilliztech/claude-context",
    "url": "https://github.com/zilliztech/claude-context",
    "description": "Code search MCP for Claude Code. Make entire codebase the context for any coding agent.",
    "stars": 12146,
    "sizeKb": 7758,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-101",
    "name": "changesets",
    "fullName": "changesets/changesets",
    "url": "https://github.com/changesets/changesets",
    "description": "🦋 A tool to manage versioning and changelogs with a focus on monorepos",
    "stars": 12134,
    "sizeKb": 6984,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-102",
    "name": "rete",
    "fullName": "retejs/rete",
    "url": "https://github.com/retejs/rete",
    "description": "JavaScript framework for visual programming",
    "stars": 12109,
    "sizeKb": 1826,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-103",
    "name": "InversifyJS",
    "fullName": "inversify/InversifyJS",
    "url": "https://github.com/inversify/InversifyJS",
    "description": "Powerful and lightweight inversion of control container. Moved to https://github.com/inversify/monorepo",
    "stars": 12074,
    "sizeKb": 3475,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-104",
    "name": "tsx",
    "fullName": "privatenumber/tsx",
    "url": "https://github.com/privatenumber/tsx",
    "description": "⚡️ TypeScript Execute | The easiest way to run TypeScript in Node.js",
    "stars": 12047,
    "sizeKb": 2843,
    "license": "MIT",
    "category": "Backend",
    "focus": "Data and service contracts",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-105",
    "name": "signature_pad",
    "fullName": "szimek/signature_pad",
    "url": "https://github.com/szimek/signature_pad",
    "description": "HTML5 canvas based smooth signature drawing",
    "stars": 11975,
    "sizeKb": 7094,
    "license": "MIT",
    "category": "Frontend",
    "focus": "State and rendering",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-106",
    "name": "giscus",
    "fullName": "giscus/giscus",
    "url": "https://github.com/giscus/giscus",
    "description": "A commenting system powered by GitHub Discussions. :octocat: :speech_balloon: :gem:",
    "stars": 11918,
    "sizeKb": 3420,
    "license": "MIT",
    "category": "Full-stack",
    "focus": "Integration boundaries",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-107",
    "name": "class-validator",
    "fullName": "typestack/class-validator",
    "url": "https://github.com/typestack/class-validator",
    "description": "Decorator-based property validation for classes.",
    "stars": 11807,
    "sizeKb": 5002,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Intermediate"
  },
  {
    "id": "curated-108",
    "name": "scira",
    "fullName": "zaidmukaddam/scira",
    "url": "https://github.com/zaidmukaddam/scira",
    "description": "Scira (Formerly MiniPerplx) is a minimalistic AI-powered search engine that helps you find information on the internet and cites it too. Powered by Vercel AI SDK!",
    "stars": 11760,
    "sizeKb": 19314,
    "license": "AGPL-3.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Advanced"
  },
  {
    "id": "curated-109",
    "name": "openwiki",
    "fullName": "langchain-ai/openwiki",
    "url": "https://github.com/langchain-ai/openwiki",
    "description": "OpenWiki is a CLI that writes and maintains agent documentation for your codebase.",
    "stars": 11752,
    "sizeKb": 1176,
    "license": "MIT",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  },
  {
    "id": "curated-110",
    "name": "reader",
    "fullName": "jina-ai/reader",
    "url": "https://github.com/jina-ai/reader",
    "description": "Convert any URL to an LLM-friendly input with a simple prefix https://r.jina.ai/",
    "stars": 11571,
    "sizeKb": 1575,
    "license": "Apache-2.0",
    "category": "Developer tooling",
    "focus": "Contract and validation",
    "difficulty": "Beginner"
  }
] satisfies CuratedRepository[];

export const CURATED_REPOSITORY_COUNT = curatedRepositories.length;

