import type { WorkspaceFile } from "../rehearsals/types";
export type BuiltInSample={name:string;language:string;files:WorkspaceFile[]};
export const builtInSamples:Record<string,BuiltInSample>={
  "sample-billing-api":{name:"billing-api",language:"TypeScript",files:[{path:"src/billing.ts",content:"export function billingRegion(profile: { region?: string }) {\n  return (profile.region ?? 'US').toUpperCase();\n}\n"},{path:"tests/billing.test.ts",content:"import { expect, it } from 'vitest';\nimport { billingRegion } from '../src/billing';\nit('defaults missing regions', () => expect(billingRegion({})).toBe('US'));\n"}]},
  "sample-inventory-worker":{name:"inventory-worker",language:"Python",files:[{path:"inventory/worker.py",content:"def normalize_item(payload):\n    warehouse = payload.get('warehouse') or 'primary'\n    return {'sku': payload['sku'], 'warehouse': warehouse}\n"},{path:"tests/test_worker.py",content:"from inventory.worker import normalize_item\n\ndef test_missing_warehouse_uses_primary():\n    assert normalize_item({'sku': 'A1'})['warehouse'] == 'primary'\n"}]},
  "sample-gateway-service":{name:"gateway-service",language:"Go",files:[{path:"internal/gateway/handler.go",content:"package gateway\n\nfunc LoadRoute() (*Route, error) {\n\troute, err := fetchRoute()\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn route, nil\n}\n"},{path:"internal/gateway/handler_test.go",content:"package gateway\n\nimport \"testing\"\n\nfunc TestLoadRouteFailure(t *testing.T) {\n\troute, err := LoadRoute()\n\tif err == nil || route != nil { t.Fatal(\"expected the route failure to propagate\") }\n}\n"}]},
  "sample-orders-platform":{name:"orders-platform",language:"Java",files:[{path:"src/main/java/app/OrderMapper.java",content:"package app;\nimport java.util.Objects;\nclass OrderMapper {\n  String region(Order order) { return Objects.requireNonNullElse(order.region(), \"US\"); }\n}\n"},{path:"src/test/java/app/OrderMapperTest.java",content:"package app;\nimport static org.junit.jupiter.api.Assertions.assertEquals;\nimport org.junit.jupiter.api.Test;\nclass OrderMapperTest { @Test void defaultsMissingRegion() { assertEquals(\"US\", new OrderMapper().region(new Order(null))); } }\n"}]},
  "sample-identity-service":{name:"identity-service",language:"C#",files:[{path:"Services/ClaimsMapper.cs",content:"namespace Identity.Services;\npublic class ClaimsMapper {\n  public string Tenant(Claims claims) {\n    var tenant = claims.Tenant ?? \"public\";\n    return tenant;\n  }\n}\n"},{path:"Tests/ClaimsMapperTests.cs",content:"using Xunit;\nnamespace Identity.Tests;\npublic class ClaimsMapperTests { [Fact] public void MissingTenantUsesPublic() { Assert.Equal(\"public\", new ClaimsMapper().Tenant(new Claims { Tenant = null })); } }\n"}]},
  "sample-event-processor":{name:"event-processor",language:"Rust",files:[{path:"src/processor.rs",content:"pub fn retry_count(value: Option<u32>) -> u32 {\n    value.unwrap_or(0)\n}\n"},{path:"tests/processor.rs",content:"use event_processor::retry_count;\n#[test]\nfn missing_retry_count_defaults_to_zero() { assert_eq!(retry_count(None), 0); }\n"}]},
};
