"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { usePlan } from "../components/PlanProvider";

type Repository = { id:string;name:string;language:string;fileCount:number };
type Draft = { id:string;repositoryId:string;repositoryName:string;title:string;signal:string;rootCause:string;targetPath:string;faultInjection:string;evidenceContract:string;validationContract:string;objective:string;status:"DRAFT" };
const empty={repositoryId:"",title:"",signal:"",rootCause:"",targetPath:"",faultInjection:"",evidenceContract:"",validationContract:"",objective:""};

export default function EnterpriseStudio() {
  const { includes, activate, activePlan } = usePlan();
  const [drafts,setDrafts]=useState<Draft[]>([]);const[repositories,setRepositories]=useState<Repository[]>([]);const[form,setForm]=useState(empty);const[notice,setNotice]=useState("");
  useEffect(()=>{const timer=window.setTimeout(()=>{const stored=window.localStorage.getItem("rr-enterprise-drafts");if(stored){try{setDrafts(JSON.parse(stored) as Draft[])}catch{/* malformed device state is ignored */}}},0);fetch("/api/team",{headers:{"x-reporehearsal-plan":activePlan}}).then(async response=>response.ok?response.json():null).then(body=>{if(body?.repositories){setRepositories(body.repositories);setForm(current=>current.repositoryId||!body.repositories[0]?current:{...current,repositoryId:body.repositories[0].id})}}).catch(()=>{/* the form can still be drafted before a repository is imported */});return()=>window.clearTimeout(timer);},[activePlan]);
  function update(name:keyof typeof empty,value:string){setForm(current=>({...current,[name]:value}));}
  function submit(event:FormEvent){event.preventDefault();const repository=repositories.find(item=>item.id===form.repositoryId);if(!repository){setNotice("Import a repository into the team owner’s library before authoring an incident.");return}const draft:Draft={id:crypto.randomUUID(),repositoryId:repository.id,repositoryName:repository.name,title:form.title.trim(),signal:form.signal.trim(),rootCause:form.rootCause.trim(),targetPath:form.targetPath.trim(),faultInjection:form.faultInjection.trim(),evidenceContract:form.evidenceContract.trim(),validationContract:form.validationContract.trim(),objective:form.objective.trim(),status:"DRAFT"};const next=[draft,...drafts];setDrafts(next);window.localStorage.setItem("rr-enterprise-drafts",JSON.stringify(next));setForm({...empty,repositoryId:repository.id});setNotice("Draft saved. Review the fault and validation contract before publishing it to your team.");}
  function remove(id:string){const next=drafts.filter(draft=>draft.id!==id);setDrafts(next);window.localStorage.setItem("rr-enterprise-drafts",JSON.stringify(next));}

  if(!includes("TEAM"))return <main className="app-page"><section className="feature-gate"><span className="badge badge-red">TEAM FEATURE</span><h1>Turn operational history into practice.</h1><p>Activate the Team preview to draft custom incident templates and explore security controls. Billing is not connected.</p><div className="actions"><button className="button button-blue" onClick={()=>activate("TEAM")}>Activate Team preview →</button><Link className="button button-ghost" href="/pricing">Compare plans</Link></div></section></main>;

  return <main className="app-page product-dashboard incident-studio"><div className="page-title-row"><div><h1>Custom incident studio</h1><p>Describe a real failure as an explicit fault injection, evidence trail, and deterministic validation contract.</p></div><Link className="button button-ghost" href="/team">Back to team</Link></div>
    <div className="enterprise-grid"><form className="panel incident-builder" onSubmit={submit}><h2>New incident draft</h2><label>Repository<select value={form.repositoryId} onChange={event=>update("repositoryId",event.target.value)} required><option value="">Choose an imported repository</option>{repositories.map(repository=><option value={repository.id} key={repository.id}>{repository.name} · {repository.language} · {repository.fileCount} files</option>)}</select></label>{!repositories.length&&<p className="studio-repository-empty">No team repositories are available. <Link href="/repositories">Import one first →</Link></p>}<label>Incident title<input value={form.title} onChange={event=>update("title",event.target.value)} placeholder="Checkout API serves stale inventory" required/></label><label>Initial production signal<textarea value={form.signal} onChange={event=>update("signal",event.target.value)} placeholder="What changed for users, logs, latency, or health?" required/></label><label>Root cause<textarea value={form.rootCause} onChange={event=>update("rootCause",event.target.value)} placeholder="The exact technical condition the participant must diagnose" required/></label><label>Target file path<input value={form.targetPath} onChange={event=>update("targetPath",event.target.value)} placeholder="src/services/inventory.ts" required/></label><label>Fault injection<textarea value={form.faultInjection} onChange={event=>update("faultInjection",event.target.value)} placeholder="Describe the narrow, reversible change applied to the isolated copy" required/></label><label>Evidence contract<textarea value={form.evidenceContract} onChange={event=>update("evidenceContract",event.target.value)} placeholder="Logs, affected records, health signals, and files that support the diagnosis" required/></label><label>Validation contract<textarea value={form.validationContract} onChange={event=>update("validationContract",event.target.value)} placeholder="Observable checks that must pass, plus shortcuts that must fail" required/></label><label>Training objective<textarea value={form.objective} onChange={event=>update("objective",event.target.value)} placeholder="What should the engineer demonstrate?" required/></label><button className="button button-dark">Save review draft</button>{notice&&<p className="studio-notice" role="status">{notice}</p>}</form>
      <aside><section className="panel enterprise-controls"><h2>Publishing safeguards</h2><div><b>Source mutation</b><span>Isolated copy only</span></div><div><b>Outbound network</b><span>Blocked</span></div><div><b>Validation</b><span>Deterministic checks</span></div><div><b>Draft approval</b><span>Manager required</span></div></section><section className="panel draft-list"><h2>{drafts.length?`${drafts.length} review draft${drafts.length===1?"":"s"}`:"No drafts yet"}</h2>{drafts.map(draft=><article key={draft.id}><b>{draft.title}</b><p>{draft.repositoryName} · {draft.targetPath}</p><small>{draft.objective}</small><button className="text-link" onClick={()=>remove(draft.id)}>Delete draft</button></article>)}</section></aside></div>
  </main>;
}
