"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { usePlan } from "../components/PlanProvider";

type Repository={id:string;name:string;language:string;fileCount:number};
type SourceType="MANUAL"|"GIT_DIFF"|"PAGERDUTY"|"DATADOG"|"JIRA";
type Draft={id:string;repositoryId:string;repositoryName:string;title:string;signal:string;rootCause:string;targetPath:string;safeSnippet:string;faultySnippet:string;evidence:string[];validationContract:string;objective:string;status:"DRAFT"|"PUBLISHED";sourceType:SourceType;sourceRef:string|null;updatedAt:string};
type Form={repositoryId:string;title:string;signal:string;rootCause:string;targetPath:string;safeSnippet:string;faultySnippet:string;evidence:string;validationContract:string;objective:string;sourceType:SourceType;sourceRef:string|null};
const empty:Form={repositoryId:"",title:"",signal:"",rootCause:"",targetPath:"",safeSnippet:"",faultySnippet:"",evidence:"",validationContract:"",objective:"",sourceType:"MANUAL",sourceRef:null};

export default function EnterpriseStudio(){const{includes,activePlan}=usePlan();const[repositories,setRepositories]=useState<Repository[]>([]),[drafts,setDrafts]=useState<Draft[]>([]),[form,setForm]=useState<Form>(empty),[mode,setMode]=useState<"manual"|"diff"|"tool">("manual"),[source,setSource]=useState(""),[provider,setProvider]=useState<"PAGERDUTY"|"DATADOG"|"JIRA">("PAGERDUTY"),[notice,setNotice]=useState(""),[busy,setBusy]=useState("");
  async function load(){const[teamResponse,incidentResponse]=await Promise.all([fetch("/api/team",{headers:{"x-reporehearsal-plan":activePlan}}),fetch("/api/team/incidents")]);if(teamResponse.ok){const body=await teamResponse.json();setRepositories(body.repositories??[]);setForm(current=>current.repositoryId||!body.repositories?.[0]?current:{...current,repositoryId:body.repositories[0].id})}if(incidentResponse.ok){const body=await incidentResponse.json();setDrafts(body.incidents??[])}}
  useEffect(()=>{let current=true;void Promise.all([fetch("/api/team",{headers:{"x-reporehearsal-plan":activePlan}}),fetch("/api/team/incidents")]).then(async([teamResponse,incidentResponse])=>{if(!current)return;if(teamResponse.ok){const body=await teamResponse.json();if(!current)return;setRepositories(body.repositories??[]);setForm(existing=>existing.repositoryId||!body.repositories?.[0]?existing:{...existing,repositoryId:body.repositories[0].id})}if(incidentResponse.ok){const body=await incidentResponse.json();if(current)setDrafts(body.incidents??[])}});return()=>{current=false}},[activePlan]);
  const update=(name:keyof Form,value:string|null)=>setForm(current=>({...current,[name]:value}));
  async function api(payload:unknown){const response=await fetch("/api/team/incidents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"The incident could not be updated.");return body}
  async function generate(){setBusy("generate");setNotice("");try{const body=await api(mode==="diff"?{action:"draft-from-diff",diff:source}:{action:"draft-from-tool",provider,payload:source});const draft=body.draft as Partial<Form>;setForm(current=>({...current,...draft,evidence:Array.isArray(draft.evidence)?draft.evidence.join("\n"):current.evidence,sourceType:(draft.sourceType??current.sourceType) as SourceType}));setMode("manual");setNotice("Drafted from the source. Review every field and choose the exact repository baseline before saving.")}catch(error){setNotice(error instanceof Error?error.message:"The source could not be converted.")}finally{setBusy("")}}
  async function submit(event:FormEvent){event.preventDefault();setBusy("save");setNotice("");try{await api({action:"save",incident:{...form,evidence:form.evidence.split("\n").map(value=>value.trim()).filter(Boolean)}});setForm(current=>({...empty,repositoryId:current.repositoryId}));setNotice("Review draft saved to the team library.");await load()}catch(error){setNotice(error instanceof Error?error.message:"The draft could not be saved.")}finally{setBusy("")}}
  async function change(id:string,action:"publish"|"unpublish"|"delete"){setBusy(id);setNotice("");try{await api({action,id});await load();setNotice(action==="publish"?"Incident published and ready to assign.":action==="delete"?"Draft deleted.":"Incident returned to draft.")}catch(error){setNotice(error instanceof Error?error.message:"The incident could not be updated.")}finally{setBusy("")}}
  if(!includes("TEAM"))return <main className="app-page"><section className="feature-gate"><span className="badge badge-red">TEAM FEATURE</span><h1>Turn operational history into practice.</h1><p>Explore the complete authoring workflow without an account. Sign in when you are ready to save executable incidents and invite a team.</p><div className="actions"><Link className="button button-dark" href="/team/studio/demo">Open Team preview →</Link><Link className="button button-ghost" href="/signin?return_to=%2Fteam%2Fstudio">Sign in to create incidents</Link></div></section></main>;
  return <main className="app-page product-dashboard incident-studio"><div className="page-title-row"><div><h1>Custom incident studio</h1><p>Build a deterministic exercise from a known-good repository boundary, a controlled fault, and observable validation.</p></div><Link className="button button-ghost" href="/team">Back to team</Link></div>
    <nav className="studio-source-tabs" aria-label="Incident source"><button className={mode==="manual"?"active":""} onClick={()=>setMode("manual")}>Write manually</button><button className={mode==="diff"?"active":""} onClick={()=>setMode("diff")}>Draft from git diff</button><button className={mode==="tool"?"active":""} onClick={()=>setMode("tool")}>Import incident export</button></nav>
    {mode!=="manual"&&<section className="panel studio-import"><div><h2>{mode==="diff"?"Paste the pull request diff":"Paste an incident-tool JSON export"}</h2><p>{mode==="diff"?"The repaired lines become the known-good contract; removed lines become the fault to inject. A manager reviews before publishing.":"PagerDuty, Datadog, and Jira exports become a first draft. Repository code is never inferred from ticket text."}</p></div>{mode==="tool"&&<label>Source<select value={provider} onChange={event=>setProvider(event.target.value as typeof provider)}><option>PAGERDUTY</option><option>DATADOG</option><option>JIRA</option></select></label>}<textarea value={source} onChange={event=>setSource(event.target.value)} placeholder={mode==="diff"?"diff --git a/src/service.ts b/src/service.ts…":"{ \"title\": \"Checkout latency\", … }"}/><button className="button button-dark" onClick={generate} disabled={busy==="generate"||!source.trim()}>{busy==="generate"?"Drafting…":"Create review draft"}</button></section>}
    {mode==="manual"&&<div className="enterprise-grid"><form className="panel incident-builder" onSubmit={submit}><h2>Incident contract</h2><label>Repository<select value={form.repositoryId} onChange={event=>update("repositoryId",event.target.value)} required><option value="">Choose an imported repository</option>{repositories.map(repo=><option value={repo.id} key={repo.id}>{repo.name} · {repo.language} · {repo.fileCount} files</option>)}</select></label>{!repositories.length&&<p className="studio-repository-empty">No team repository is available. <Link href="/repositories">Import one first →</Link></p>}<label>Incident title<input value={form.title} onChange={event=>update("title",event.target.value)} required/></label><label>Initial production signal<textarea value={form.signal} onChange={event=>update("signal",event.target.value)} required/></label><label>Root cause<textarea value={form.rootCause} onChange={event=>update("rootCause",event.target.value)} required/></label><label>Target file path<input value={form.targetPath} onChange={event=>update("targetPath",event.target.value)} placeholder="src/services/inventory.ts" required/></label><label>Known-good snippet<textarea className="code-contract" value={form.safeSnippet} onChange={event=>update("safeSnippet",event.target.value)} placeholder="Exact text currently present in the repository" required/></label><label>Fault to inject<textarea className="code-contract" value={form.faultySnippet} onChange={event=>update("faultySnippet",event.target.value)} placeholder="Narrow replacement used only in the isolated copy" required/></label><label>Evidence contract<textarea value={form.evidence} onChange={event=>update("evidence",event.target.value)} placeholder="One log, record, or health signal per line" required/></label><label>Validation contract<textarea value={form.validationContract} onChange={event=>update("validationContract",event.target.value)} required/></label><label>Training objective<textarea value={form.objective} onChange={event=>update("objective",event.target.value)} required/></label><button className="button button-dark" disabled={busy==="save"}>{busy==="save"?"Saving…":"Save review draft"}</button>{notice&&<p className="studio-notice" role="status">{notice}</p>}</form>
      <aside><section className="panel enterprise-controls"><h2>Publishing safeguards</h2><div><b>Source mutation</b><span>Isolated copy only</span></div><div><b>Authoring</b><span>Manager reviewed</span></div><div><b>Validation</b><span>Exact baseline contract</span></div><div><b>Network</b><span>Blocked</span></div></section><section className="panel draft-list"><h2>Team library</h2>{drafts.length===0&&<p>No incidents yet.</p>}{drafts.map(draft=><article key={draft.id}><div><b>{draft.title}</b><span className={`team-status ${draft.status==="PUBLISHED"?"active":"invited"}`}>{draft.status.toLowerCase()}</span></div><p>{draft.repositoryName} · {draft.targetPath}</p><small>{draft.sourceType.replace("_"," ")}</small><div>{draft.status==="DRAFT"?<button className="text-link" onClick={()=>change(draft.id,"publish")} disabled={busy===draft.id}>Publish</button>:<button className="text-link" onClick={()=>change(draft.id,"unpublish")} disabled={busy===draft.id}>Unpublish</button>}<button className="text-link" onClick={()=>change(draft.id,"delete")} disabled={busy===draft.id}>Delete</button></div></article>)}</section></aside></div>}
  </main>}
