"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { incidents } from "../../../src/data";
import type { AccountMode } from "../../../src/accounts/types";

export default function RehearsalSetup() {
  const router = useRouter(); const [incidentId, setIncidentId] = useState(incidents[0].id); const [difficulty, setDifficulty] = useState("INTERMEDIATE");
  const [mode, setMode] = useState<AccountMode>("GUIDED"); const [limit, setLimit] = useState(25);
  useEffect(() => { fetch("/api/account").then(response => response.ok ? response.json() : null).then(data => { if (data?.profile) { setMode(data.profile.defaultMode); setLimit(data.profile.defaultTimeLimit); } }).catch(() => undefined); }, []);
  function start(event: FormEvent) { event.preventDefault(); const params = new URLSearchParams({ incident: incidentId, difficulty, mode, limit: String(limit) }); router.push(`/rehearsals/demo/preparing?${params}`); }
  return <main className="app-page"><div className="page-title-row"><div><p className="eyebrow">NEW REHEARSAL</p><h1>Configure the incident</h1><p>Choose a deterministic scenario and the level of coaching you want.</p></div></div><form onSubmit={start}><div className="scenario-grid">{incidents.map((incident, index) => <button type="button" className={`scenario-card scenario-choice ${incidentId === incident.id ? "selected" : ""}`} key={incident.id} onClick={() => setIncidentId(incident.id)} aria-pressed={incidentId === incident.id}><span className={`badge ${index === 0 ? "badge-red" : "badge-blue"}`}>{incident.difficulty.toUpperCase()}</span><h2>{incident.name}</h2><p>{incident.summary}</p><div className="tag-row"><span className="tag">{incident.category.replace("_", " ")}</span><span className="tag">{index === 1 ? "10–15 min" : "15–25 min"}</span></div><b className="scenario-select-label">{incidentId === incident.id ? "✓ Selected" : "Select incident"}</b></button>)}</div><section className="panel exercise-settings"><span className="panel-label">EXERCISE SETTINGS</span><div className="grid-4"><label>Difficulty<select value={difficulty} onChange={event => setDifficulty(event.target.value)}><option value="BEGINNER">Beginner</option><option value="INTERMEDIATE">Intermediate</option></select></label><label>Mode<select value={mode} onChange={event => setMode(event.target.value as AccountMode)}><option value="GUIDED">Guided coaching</option><option value="INDEPENDENT">Independent</option><option value="INTERVIEW">Interview mode</option></select></label><label>Time limit<select value={limit} onChange={event => setLimit(Number(event.target.value))}><option value={15}>15 minutes</option><option value={25}>25 minutes</option><option value={45}>45 minutes</option><option value={60}>60 minutes</option></select></label><label>Repository<select><option>RepoRehearsal Billing Demo</option></select></label></div>{mode === "INTERVIEW" && <div className="interview-callout"><span className="badge badge-blue">INTERVIEW MODE</span><p>A visible countdown runs throughout the exercise. Coaching hints are disabled, and the report emphasizes evidence, verification, and communication for interviewer review.</p></div>}<div className="setup-submit"><p><b>{incidents.find(item => item.id === incidentId)?.name}</b><br /><small>{mode.toLowerCase()} · {limit} minutes · {difficulty.toLowerCase()}</small></p><button className="button button-blue">Prepare isolated rehearsal →</button></div></section></form></main>;
}
