"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import { incidents } from "../../../src/data";
import { GENERATED_INCIDENT_ID } from "../../../src/incidents/brain";

const presets:Record<string,{difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED";mode:"GUIDED"|"INDEPENDENT";timeLimitMinutes:number}>=Object.fromEntries(incidents.map(item=>{const difficulty=item.difficulty.toUpperCase() as "BEGINNER"|"INTERMEDIATE"|"ADVANCED";return[item.id,{difficulty,mode:difficulty==="BEGINNER"?"GUIDED":"INDEPENDENT",timeLimitMinutes:difficulty==="ADVANCED"?45:difficulty==="BEGINNER"?20:30}]}));
export default function RehearsalSetup(){const router=useRouter(),search=useSearchParams();const repositoryId=search.get("repositoryId")??"billing-demo";const generated=search.get("generated")==="1";const requestedIncident=search.get("incidentId");const initialIncident=generated?GENERATED_INCIDENT_ID:incidents.some(item=>item.id===requestedIncident)?requestedIncident!:incidents[0].id;const [step,setStep]=useState(1),[incidentId,setIncidentId]=useState(initialIncident),[difficulty,setDifficulty]=useState<"BEGINNER"|"INTERMEDIATE"|"ADVANCED">(presets[initialIncident]?.difficulty??"INTERMEDIATE"),[status,setStatus]=useState("idle"),[message,setMessage]=useState("");const selected=generated?{id:GENERATED_INCIDENT_ID,name:"Repository-derived incident",summary:"RepoRehearsal will inspect this source snapshot and inject a safe, deterministic fault at a real code boundary.",category:"external_dependency" as const}:incidents.find(item=>item.id===incidentId)??incidents[0];const preset=generated?{difficulty,mode:"INDEPENDENT" as const,timeLimitMinutes:30}:presets[selected.id];const repoName=search.get("repositoryName")??(repositoryId==="billing-demo"?"RepoRehearsal Billing Demo":"Imported repository");const language=search.get("language")??(repositoryId==="billing-demo"?"TypeScript":"Detected from source");
async function start(event:FormEvent){event.preventDefault();setStatus("creating");try{const repositoryAccessToken=sessionStorage.getItem(`rr-repository-${repositoryId}`);const response=await fetch("/api/rehearsals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({repositoryId,repositoryAccessToken,incidentTemplateId:selected.id,difficulty,mode:preset.mode,timeLimitMinutes:preset.timeLimitMinutes})});const data=await response.json() as {session?:{id:string};accessToken?:string;error?:{message?:string}};if(!response.ok||!data.session||!data.accessToken)throw new Error(data.error?.message??"The rehearsal could not be created.");sessionStorage.setItem(`rr-session-${data.session.id}`,data.accessToken);router.push(`/rehearsals/${data.session.id}/preparing`)}catch(error){setMessage(error instanceof Error?error.message:"The rehearsal could not be created.");setStatus("error")}}
return <main className="rehearsal-wizard rr-narrow"><ol className="wizard-stepper">{["Repository","Failure type","Confirm"].map((label,index)=><li className={step===index+1?"active":step>index+1?"done":""} key={label}><i>{step>index+1?"✓":index+1}</i><span>{label}</span></li>)}</ol><form className="wizard-panel" onSubmit={start}>{step===1&&<section><h2>Choose a repository</h2><button type="button" className="wizard-radio selected"><i/><span><b>{repoName}</b><small>{language} · isolated built-in snapshot</small></span></button><Link className="wizard-connect" href="/repositories">Choose another repository ↗</Link></section>}{step===2&&<section><h2>Choose the kind of failure</h2>{generated?<div className="wizard-incidents"><button type="button" className="selected"><code>AI</code><span><b>{selected.name}</b><small>{selected.summary}</small></span></button></div>:<div className="wizard-incidents">{incidents.map(item=><button type="button" className={incidentId===item.id?"selected":""} onClick={()=>{setIncidentId(item.id);setDifficulty(presets[item.id].difficulty)}} key={item.id}><code>{item.category==="database"?"DB":item.category==="configuration"?"CFG":"API"}</code><span><b>{item.name}</b><small>{item.summary}</small></span></button>)}</div>}<fieldset><legend>Difficulty</legend>{(["BEGINNER","INTERMEDIATE","ADVANCED"] as const).map(item=><button type="button" className={difficulty===item?"active":""} onClick={()=>setDifficulty(item)} key={item}>{item.toLowerCase()}</button>)}</fieldset></section>}{step===3&&<section><h2>Ready to rehearse</h2><dl className="wizard-summary"><div><dt>Repository</dt><dd>{repoName}</dd></div><div><dt>Failure type</dt><dd>{selected.name}</dd></div><div><dt>Difficulty</dt><dd>{difficulty.toLowerCase()}</dd></div><div><dt>Est. time</dt><dd>{preset.timeLimitMinutes} minutes</dd></div><div><dt>Language</dt><dd>{language}</dd></div></dl><aside>A deterministic fault is injected only after the clean baseline passes. Your source stays untouched.</aside><button className="button button-blue wizard-create" disabled={status==="creating"}>{status==="creating"?"Creating workspace…":"Create rehearsal →"}</button>{message&&<p className="form-error">{message}</p>}</section>}<footer><button type="button" className="text-link" disabled={step===1} onClick={()=>setStep(value=>Math.max(1,value-1))}>← Back</button>{step<3&&<button type="button" className="button button-dark" onClick={()=>setStep(value=>Math.min(3,value+1))}>Continue</button>}</footer></form></main>}
