"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import { incidents } from "../../../src/data";

const presets:Record<string,{difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED";mode:"GUIDED"|"INDEPENDENT";timeLimitMinutes:number}>={"db-required-field-migration-v1":{difficulty:"INTERMEDIATE",mode:"GUIDED",timeLimitMinutes:25},"container-host-config-v1":{difficulty:"BEGINNER",mode:"GUIDED",timeLimitMinutes:15},"provider-schema-drift-v1":{difficulty:"INTERMEDIATE",mode:"INDEPENDENT",timeLimitMinutes:25},"webhook-replay-idempotency-v1":{difficulty:"ADVANCED",mode:"INDEPENDENT",timeLimitMinutes:45}};
export default function RehearsalSetup(){const router=useRouter(),search=useSearchParams();const repositoryId=search.get("repositoryId")??"billing-demo";const [step,setStep]=useState(1),[incidentId,setIncidentId]=useState(incidents[0].id),[difficulty,setDifficulty]=useState<"BEGINNER"|"INTERMEDIATE"|"ADVANCED">("INTERMEDIATE"),[status,setStatus]=useState("idle"),[message,setMessage]=useState("");const selected=incidents.find(item=>item.id===incidentId)??incidents[0];const preset=presets[selected.id];const repoName=repositoryId==="billing-demo"?"RepoRehearsal Billing Demo":"Your imported repository";
async function start(event:FormEvent){event.preventDefault();setStatus("creating");try{const repositoryAccessToken=sessionStorage.getItem(`rr-repository-${repositoryId}`);const response=await fetch("/api/rehearsals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({repositoryId,repositoryAccessToken,incidentTemplateId:selected.id,difficulty,mode:preset.mode,timeLimitMinutes:preset.timeLimitMinutes})});const data=await response.json() as {session?:{id:string};accessToken?:string;error?:{message?:string}};if(!response.ok||!data.session||!data.accessToken)throw new Error(data.error?.message??"The rehearsal could not be created.");sessionStorage.setItem(`rr-session-${data.session.id}`,data.accessToken);router.push(`/rehearsals/${data.session.id}/preparing`)}catch(error){setMessage(error instanceof Error?error.message:"The rehearsal could not be created.");setStatus("error")}}
return <main className="rehearsal-wizard rr-narrow"><ol className="wizard-stepper">{["Repository","Failure type","Confirm"].map((label,index)=><li className={step===index+1?"active":step>index+1?"done":""} key={label}><i>{step>index+1?"✓":index+1}</i><span>{label}</span></li>)}</ol><form className="wizard-panel" onSubmit={start}>{step===1&&<section><h2>Choose a repository</h2><button type="button" className="wizard-radio selected"><i/><span><b>{repoName}</b><small>TypeScript · DB · CFG · API</small></span></button><Link className="wizard-connect" href="/repositories">Connect your own ↗</Link></section>}{step===2&&<section><h2>Choose the kind of failure</h2><div className="wizard-incidents">{incidents.map(item=><button type="button" className={incidentId===item.id?"selected":""} onClick={()=>{setIncidentId(item.id);setDifficulty(presets[item.id].difficulty)}} key={item.id}><code>{item.category==="database"?"DB":item.category==="configuration"?"CFG":"API"}</code><span><b>{item.name}</b><small>{item.summary}</small></span></button>)}</div><fieldset><legend>Difficulty</legend>{(["BEGINNER","INTERMEDIATE","ADVANCED"] as const).map(item=><button type="button" className={difficulty===item?"active":""} onClick={()=>setDifficulty(item)} key={item}>{item.toLowerCase()}</button>)}</fieldset></section>}{step===3&&<section><h2>Ready to rehearse</h2><dl className="wizard-summary"><div><dt>Repository</dt><dd>{repoName}</dd></div><div><dt>Failure type</dt><dd>{selected.name}</dd></div><div><dt>Difficulty</dt><dd>{difficulty.toLowerCase()}</dd></div><div><dt>Est. time</dt><dd>{preset.timeLimitMinutes} minutes</dd></div><div><dt>Language</dt><dd>TypeScript</dd></div></dl><aside>A deterministic fault is injected only after the clean baseline passes. Your source stays untouched.</aside><button className="button button-blue wizard-create" disabled={status==="creating"}>{status==="creating"?"Creating workspace…":"Create rehearsal →"}</button>{message&&<p className="form-error">{message}</p>}</section>}<footer><button type="button" className="text-link" disabled={step===1} onClick={()=>setStep(value=>Math.max(1,value-1))}>← Back</button>{step<3&&<button type="button" className="button button-dark" onClick={()=>setStep(value=>Math.min(3,value+1))}>Continue</button>}</footer></form></main>}
