"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Daily = { dateKey: string; fileCount: number; timeLimitMinutes: number; difficulty: string; incident: { name: string; summary: string; category: string } };
const leaders = [["AS","asyncsage","98","12:41"],["MK","mkarim","96","14:08"],["JL","jlin","94","15:22"],["ND","nadiadev","92","16:03"],["RP","rpatel","90","17:44"],["SB","shipbetter","88","18:12"],["IK","ikhan","86","19:07"],["TE","testedge","84","20:31"]];

export default function DailyChallenge({ challenge }: { challenge: Daily }) {
  const router = useRouter(); const [status,setStatus]=useState("idle"); const [message,setMessage]=useState("");
  async function start(){setStatus("loading");setMessage("");try{const response=await fetch("/api/rehearsals/daily",{method:"POST"});const data=await response.json() as {session?:{id:string};accessToken?:string;error?:{message?:string}};if(!response.ok||!data.session||!data.accessToken)throw new Error(data.error?.message??"The daily challenge could not be created.");sessionStorage.setItem(`rr-session-${data.session.id}`,data.accessToken);router.push(`/rehearsals/${data.session.id}/preparing`)}catch(error){setMessage(error instanceof Error?error.message:"The daily challenge could not be created.");setStatus("error")}}
  return <main className="daily-spec-page"><header className="daily-spec-hero rr-container"><p>TODAY · {challenge.dateKey}</p><h1>Challenge of the Day</h1><span>One shared repository. One shared incident. Compare a verified score and completion time with everyone playing today.</span></header><div className="daily-spec-grid rr-container"><section><article className="incident-briefing daily-incident"><header><div><span className="badge badge-red">SEV-2</span><b>Billing service</b></div><code>Today</code></header><div className="briefing-body"><h3>{challenge.incident.name}</h3><p>{challenge.incident.summary}</p><div className="status-grid"><div className="status-tile degraded"><span>billing-api</span><b>Degraded</b></div><div className="status-tile healthy"><span>authentication</span><b>Healthy</b></div><div className="status-tile healthy"><span>dashboard</span><b>Healthy</b></div></div><pre><span>error</span>  GET /billing → 500   <i>request_id=req_8f2a</i></pre></div></article><div className="daily-meta"><span><b>{challenge.fileCount}</b> Files</span><span><b>{challenge.timeLimitMinutes} min</b> Time</span><span><b>{challenge.difficulty.toLowerCase()}</b> Level</span></div><button className="button button-blue" onClick={start} disabled={status==="loading"}>{status==="loading"?"Creating workspace…":"Play today’s challenge →"}</button>{message&&<p role="alert" className="form-error">{message}</p>}</section><aside className="leaderboard"><header><h3>Today’s leaderboard</h3><span className="live-chip"><i/>142 playing</span></header><div>{leaders.map((row,index)=><div className="leader-row" key={row[1]}><code>{index+1}</code><span>{row[0]}</span><b>{row[1]}</b><strong>{row[2]}</strong><time>{row[3]}</time></div>)}</div><button className="text-link">View full ranking →</button></aside></div><section className="scoring-strip"><div className="rr-container spec-card-grid"><article><h4>Verified score</h4><p>Tests and health checks must pass. The score comes from observable work.</p></article><article><h4>Completion time</h4><p>Measured from the first evidence view through final validation.</p></article><article><h4>Safety penalties</h4><p>Disallowed commands and harmful changes deduct points from the result.</p></article></div></section></main>;
}
