"use client";

import { useState } from "react";
import { plans, type PlanId } from "../../src/billing/plans";
import { usePlan } from "../components/PlanProvider";

const featureRows: { group: string; label: string; detail: string; included: Record<PlanId, boolean> }[] = [
  { group: "PRACTICE", label: "Four starter incidents", detail: "Database, configuration, provider drift, and webhook replay cases", included: { FREE: true, PRO: true, TEAM: true, ENTERPRISE: true } },
  { group: "PRACTICE", label: "Public GitHub and local uploads", detail: "Analyze bounded public repositories, folders, and ZIP archives", included: { FREE: true, PRO: true, TEAM: true, ENTERPRISE: true } },
  { group: "PRACTICE", label: "Deterministic validation", detail: "Known checks determine repair quality without subjective scoring", included: { FREE: true, PRO: true, TEAM: true, ENTERPRISE: true } },
  { group: "REPORTING", label: "Basic after-action report", detail: "Root cause, evidence used, validation results, and prevention", included: { FREE: true, PRO: true, TEAM: true, ENTERPRISE: true } },
  { group: "REPORTING", label: "Advanced skill analysis", detail: "Diagnosis, evidence, repair, verification, and prevention signals", included: { FREE: false, PRO: true, TEAM: true, ENTERPRISE: true } },
  { group: "PERSONAL", label: "Interview mode", detail: "Timed practice with hints disabled and communication scoring", included: { FREE: false, PRO: true, TEAM: true, ENTERPRISE: true } },
  { group: "PERSONAL", label: "Saved progress with ChatGPT", detail: "Keep rehearsal history, preferences, and readiness metrics", included: { FREE: false, PRO: true, TEAM: true, ENTERPRISE: true } },
  { group: "PERSONAL", label: "Reusable repository library", detail: "Retain safe source snapshots for future rehearsals", included: { FREE: false, PRO: true, TEAM: true, ENTERPRISE: true } },
  { group: "TEAM", label: "Team readiness dashboard", detail: "See completion, performance, and recurring skill gaps", included: { FREE: false, PRO: false, TEAM: true, ENTERPRISE: true } },
  { group: "TEAM", label: "Learning-path assignments", detail: "Assign focused database, systems, and provider practice", included: { FREE: false, PRO: false, TEAM: true, ENTERPRISE: true } },
  { group: "TEAM", label: "Manager reporting", detail: "Track program progress and readiness improvement", included: { FREE: false, PRO: false, TEAM: true, ENTERPRISE: true } },
  { group: "ENTERPRISE", label: "Custom incident studio", detail: "Turn operational patterns into controlled training templates", included: { FREE: false, PRO: false, TEAM: false, ENTERPRISE: true } },
  { group: "ENTERPRISE", label: "Security and retention controls", detail: "Define source retention, network, and execution safeguards", included: { FREE: false, PRO: false, TEAM: false, ENTERPRISE: true } },
  { group: "ENTERPRISE", label: "Audit-ready exports", detail: "Export program activity for internal review", included: { FREE: false, PRO: false, TEAM: false, ENTERPRISE: true } },
];

function DashboardMock({ plan }: { plan: PlanId }) {
  if (plan === "FREE") return <div className="mock-dashboard mock-free"><div className="mock-topline"><div><span>FREE PRACTICE</span><h3>Choose your next incident</h3></div><b>4 CASES</b></div><div className="mock-case-grid"><article><span>DB</span><b>Required field migration</b><small>INTERMEDIATE · 25 MIN</small></article><article><span>CFG</span><b>Container host mismatch</b><small>BEGINNER · 15 MIN</small></article><article><span>API</span><b>Provider schema drift</b><small>INTERMEDIATE · 25 MIN</small></article><article><span>PAY</span><b>Webhook replay</b><small>ADVANCED · 45 MIN</small></article></div></div>;
  if (plan === "PRO") return <div className="mock-dashboard mock-pro"><div className="mock-topline"><div><span>PERSONAL READINESS</span><h3>Your investigation profile</h3></div><b>84 / 100</b></div><div className="mock-metrics"><article><small>COMPLETED</small><strong>12</strong><i>+3 this month</i></article><article><small>AVG. DIAGNOSIS</small><strong>18m</strong><i>4m faster</i></article><article><small>TOP SKILL</small><strong>91%</strong><i>Diagnosis</i></article></div><div className="mock-chart"><div><span>Diagnosis</span><i style={{ width: "91%" }} /></div><div><span>Evidence</span><i style={{ width: "86%" }} /></div><div><span>Verification</span><i style={{ width: "79%" }} /></div><div><span>Prevention</span><i style={{ width: "64%" }} /></div></div></div>;
  if (plan === "TEAM") return <div className="mock-dashboard mock-team"><div className="mock-topline"><div><span>TEAM READINESS</span><h3>Platform engineering</h3></div><b>18 MEMBERS</b></div><div className="mock-metrics"><article><small>COMPLETION</small><strong>78%</strong><i>42 rehearsals</i></article><article><small>READINESS</small><strong>81</strong><i>+6 this quarter</i></article><article><small>SKILL GAP</small><strong>63%</strong><i>Prevention</i></article></div><div className="mock-team-row"><b>Safe database rollouts</b><span><i style={{ width: "72%" }} /></span><small>13 / 18</small></div><div className="mock-team-row"><b>Provider resilience</b><span><i style={{ width: "44%" }} /></span><small>8 / 18</small></div></div>;
  return <div className="mock-dashboard mock-enterprise"><div className="mock-topline"><div><span>RELIABILITY PROGRAM</span><h3>Enterprise controls</h3></div><b>POLICY ACTIVE</b></div><div className="mock-enterprise-grid"><article><small>CUSTOM TEMPLATES</small><strong>24</strong><p>6 created from internal postmortems</p></article><article><small>RETENTION</small><strong>24h</strong><p>Automatic source and workspace expiry</p></article><article><small>NETWORK</small><strong>BLOCKED</strong><p>Approval required for outbound access</p></article><article><small>AUDIT EXPORT</small><strong>READY</strong><p>Program activity packaged for review</p></article></div></div>;
}

export default function PricingClient() {
  const { activePlan, activate, plan: current } = usePlan();
  const [exploredPlan, setExploredPlan] = useState<PlanId>("FREE");

  function choose(plan: PlanId) {
    activate(plan);
    document.getElementById("plan-confirmation")?.scrollIntoView({ behavior: "smooth", block: "center" });
  }

  function explore(plan: PlanId) {
    setExploredPlan(plan);
    window.requestAnimationFrame(() => document.getElementById("feature-breakdown")?.scrollIntoView({ behavior: "smooth", block: "start" }));
  }

  return <main className="pricing-page">
    <section className="pricing-hero page-pad"><p className="eyebrow">PRICING PREVIEW</p><h1>Practice alone.<br /><em>Build readiness together.</em></h1><p>Payments are not connected yet. Activate any plan now to explore its product experience with no checkout or card details.</p><div id="plan-confirmation" className="preview-access-note"><span className="pulse" /><div><b>{current.name} preview is active</b><small>Your selection is remembered only on this device. Change plans whenever you like.</small></div></div></section>
    <section className="pricing-grid page-pad" aria-label="RepoRehearsal plans">{plans.map(plan => <article className={`pricing-card ${plan.featured ? "featured" : ""} ${activePlan === plan.id ? "active" : ""}`} key={plan.id}><div className="pricing-card-head"><span className="panel-label">{plan.eyebrow}</span>{activePlan === plan.id && <span className="badge badge-green">ACTIVE PREVIEW</span>}</div><h2>{plan.name}</h2><p>{plan.description}</p><div className="plan-price"><strong>{plan.price}</strong><span>{plan.cadence}</span></div><ul>{plan.features.map(feature => <li key={feature}><span>✓</span>{feature}</li>)}</ul><button className={`button ${plan.featured ? "button-blue" : "button-dark"}`} onClick={() => choose(plan.id)}>{activePlan === plan.id ? `${plan.name} is active` : plan.cta}</button><button className="text-link plan-open-link" onClick={() => explore(plan.id)}>Open included features →</button></article>)}</section>
    <section className="feature-breakdown page-pad" id="feature-breakdown"><div className="feature-breakdown-head"><div><p className="eyebrow">COMPLETE FEATURE BREAKDOWN</p><h2>See exactly what each plan includes.</h2><p>Checks are included features. Dashes show where the capability becomes available in a higher tier.</p></div><div className="feature-plan-tabs" aria-label="Select dashboard preview">{plans.map(plan => <button className={exploredPlan === plan.id ? "active" : ""} onClick={() => setExploredPlan(plan.id)} aria-pressed={exploredPlan === plan.id} key={plan.id}>{plan.name}</button>)}</div></div><div className="feature-table-scroll"><table className="feature-table"><thead><tr><th scope="col">Capability</th>{plans.map(plan => <th scope="col" className={exploredPlan === plan.id ? "selected" : ""} key={plan.id}><button onClick={() => setExploredPlan(plan.id)}>{plan.name}<small>{plan.price}</small></button></th>)}</tr></thead><tbody>{featureRows.map((feature, index) => <tr key={feature.label} className={index === 0 || featureRows[index - 1].group !== feature.group ? "group-start" : ""}><th scope="row"><small>{feature.group}</small><b>{feature.label}</b><span>{feature.detail}</span></th>{plans.map(plan => <td className={exploredPlan === plan.id ? "selected" : ""} key={plan.id}>{feature.included[plan.id] ? <span className="feature-check" aria-label={`${feature.label} is included in ${plan.name}`}>✓</span> : <span className="feature-dash" aria-label={`${feature.label} is not included in ${plan.name}`}>—</span>}</td>)}</tr>)}</tbody></table></div>
      <div className="dashboard-preview"><div className="dashboard-preview-copy"><span className="badge badge-blue">SAMPLE DASHBOARD</span><p className="eyebrow">{plans.find(plan => plan.id === exploredPlan)?.name.toUpperCase()} EXPERIENCE</p><h2>{exploredPlan === "FREE" ? "Start with realistic practice." : exploredPlan === "PRO" ? "Turn repetitions into personal readiness." : exploredPlan === "TEAM" ? "Manage a measurable learning program." : "Operationalize incident training at scale."}</h2><p>This compact preview shows the primary dashboard available at this tier. Preview values are illustrative.</p><button className="button button-blue" onClick={() => choose(exploredPlan)}>Activate {plans.find(plan => plan.id === exploredPlan)?.name} preview →</button></div><DashboardMock plan={exploredPlan} /></div>
    </section>
    <section className="pricing-explainer page-pad"><div><p className="eyebrow">THE COMMERCIAL MODEL</p><h2>Pay for depth, persistence, and coordination.</h2></div><div className="pricing-principles"><article><b>Public practice stays public</b><p>The four starter incidents, public GitHub links, and temporary local uploads remain free.</p></article><article><b>Individuals buy better feedback</b><p>Pro adds interview conditions, persistent progress, and a deeper breakdown of investigation skills.</p></article><article><b>Teams buy readiness visibility</b><p>Assignments, reporting, shared programs, and custom incident design create the organizational value.</p></article></div></section>
  </main>;
}
