"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { plans, priceForCadence, type BillingCadence, type PlanId } from "../../src/billing/plans";
import { usePlan } from "../components/PlanProvider";

const featureRows: { group: string; label: string; detail: string; href?: string; included: Record<PlanId, boolean | string> }[] = [
  { group: "PRACTICE", label: "Incident library", detail: "Free includes 10 fixed incidents. Every curated repository produces at least one repository-specific challenge, for 120+ starting scenarios on Pro and Team.", included: { FREE: "10 incidents", PRO: "120+ scenarios", TEAM: "120+ + custom" } },
  { group: "PRACTICE", label: "Challenge of the Day", detail: "The same five-file challenge, prompt, and scoring contract for everyone each day", included: { FREE: true, PRO: true, TEAM: true } },
  { group: "PRACTICE", label: "Repository imports", detail: "Analyze public GitHub repositories, folders, and ZIP archives after sign-in", included: { FREE: "20 MB", PRO: "75 MB", TEAM: "Unlimited" } },
  { group: "PRACTICE", label: "Curated repository roulette", detail: "Choose or randomly draw from 110 vetted public projects", included: { FREE: false, PRO: true, TEAM: true } },
  { group: "PRACTICE", label: "Language-aware incidents", detail: "Repository-specific issues across major application languages", included: { FREE: true, PRO: true, TEAM: true } },
  { group: "REPORTING", label: "Deterministic grading", detail: "Zero for untouched submissions and negative scores for regressions", included: { FREE: true, PRO: true, TEAM: true } },
  { group: "REPORTING", label: "Advanced grading report", detail: "Category rationale, evidence gaps, validation, and prevention", included: { FREE: false, PRO: true, TEAM: true } },
  { group: "PERSONAL", label: "Interview mode", detail: "Timed practice with hints disabled and communication scoring", included: { FREE: false, PRO: true, TEAM: true } },
  { group: "PERSONAL", label: "Saved progress and repository library", detail: "Keep reports, preferences, results, and safe source snapshots", included: { FREE: false, PRO: true, TEAM: true } },
  { group: "TEAM", label: "Five member seats and assignments", detail: "Invite five people, assign repositories to everyone or individuals, and review verified results", included: { FREE: false, PRO: false, TEAM: true } },
  { group: "TEAM", label: "Custom incident studio", detail: "Turn operational patterns into controlled training templates", href: "/team/studio", included: { FREE: false, PRO: false, TEAM: true } },
  { group: "TEAM", label: "Security, retention, and audit controls", detail: "Configure safeguards and export program activity for review", included: { FREE: false, PRO: false, TEAM: true } },
];

function DashboardMock({ plan }: { plan: PlanId }) {
  if (plan === "FREE") return <div className="mock-dashboard mock-free"><div className="mock-topline"><div><span>FREE PRACTICE</span><h3>Choose your next incident</h3></div><b>10 FIXED CASES</b></div><div className="mock-case-grid"><article><span>DB</span><b>Required field migration</b><small>INTERMEDIATE · 30 MIN</small></article><article><span>PERF</span><b>N+1 order lookup</b><small>INTERMEDIATE · 30 MIN</small></article><article><span>AUTH</span><b>Inverted role authorization</b><small>ADVANCED · 45 MIN</small></article><article><span>OPS</span><b>Cascading retry storm</b><small>ADVANCED · 45 MIN</small></article></div></div>;
  if (plan === "PRO") return <div className="mock-dashboard mock-pro"><div className="mock-topline"><div><span>PERSONAL READINESS</span><h3>Your investigation profile</h3></div><b>75 MB CAP</b></div><div className="mock-metrics"><article><small>COMPLETED</small><strong>12</strong><i>+3 this month</i></article><article><small>AVG. DIAGNOSIS</small><strong>18m</strong><i>4m faster</i></article><article><small>TOP SKILL</small><strong>91%</strong><i>Diagnosis</i></article></div><div className="mock-chart"><div><span>Diagnosis</span><i style={{ width: "91%" }} /></div><div><span>Evidence</span><i style={{ width: "86%" }} /></div><div><span>Verification</span><i style={{ width: "79%" }} /></div><div><span>Prevention</span><i style={{ width: "64%" }} /></div></div></div>;
  return <div className="mock-dashboard mock-team"><div className="mock-topline"><div><span>TEAM READINESS</span><h3>Complete reliability program</h3></div><b>UNLIMITED</b></div><div className="mock-metrics"><article><small>COMPLETION</small><strong>78%</strong><i>42 rehearsals</i></article><article><small>CUSTOM CASES</small><strong>24</strong><i>6 internal patterns</i></article><article><small>AUDIT STATUS</small><strong>READY</strong><i>Export enabled</i></article></div><div className="mock-team-row"><b>Safe database rollouts</b><span><i style={{ width: "72%" }} /></span><small>13 / 18</small></div><div className="mock-team-row"><b>Provider resilience</b><span><i style={{ width: "44%" }} /></span><small>8 / 18</small></div></div>;
}

export default function PricingClient() {
  const { activePlan } = usePlan();
  const router = useRouter();
  const [exploredPlan, setExploredPlan] = useState<PlanId>("FREE");
  const [billing, setBilling] = useState<BillingCadence>("monthly");

  function choose(plan: PlanId) {
    router.push(`/onboarding/account?plan=${plan}&billing=${billing}`);
  }

  function explore(plan: PlanId) {
    setExploredPlan(plan);
    window.requestAnimationFrame(() => document.getElementById("feature-breakdown")?.scrollIntoView({ behavior: "smooth", block: "start" }));
  }

  return <main className="pricing-page">
    <section className="pricing-hero page-pad"><h1>Pricing</h1><p>Start free. Upgrade when your team is ready to rehearse together.</p><div className="billing-toggle"><button className={billing === "weekly" ? "active" : ""} onClick={() => setBilling("weekly")}>Weekly</button><button className={billing === "monthly" ? "active" : ""} onClick={() => setBilling("monthly")}>Monthly</button><button className={billing === "annual" ? "active" : ""} onClick={() => setBilling("annual")}>Annual</button><span>{billing === "annual" ? "Save 20%" : billing === "weekly" ? "Flexible access" : "Standard billing"}</span></div></section>
    <section className="pricing-grid page-pad" aria-label="RepoRehearsal plans">{plans.map(plan => { const displayed=priceForCadence(plan,billing); return <article className={`pricing-card ${plan.featured ? "featured" : ""} ${activePlan === plan.id ? "active" : ""}`} key={plan.id}>{plan.featured && <span className="popular-chip">Most popular</span>}<div className="pricing-card-head"><span className="panel-label">{plan.eyebrow}</span>{activePlan === plan.id && <span className="badge badge-green">ACTIVE</span>}</div><h2>{plan.name}</h2><p>{plan.description}</p><div className="plan-price" key={`${plan.id}-${billing}`} data-billing={billing} aria-live="polite"><strong>{displayed.price}</strong><span>{displayed.cadence}{displayed.monthlyEquivalent && <small>{displayed.monthlyEquivalent}</small>}</span></div><ul>{plan.features.map(feature => <li key={feature}><span>✓</span>{feature}</li>)}</ul><button className={`button ${plan.featured ? "button-blue" : "button-dark"}`} onClick={() => choose(plan.id)}>{activePlan === plan.id ? `${plan.name} is active` : plan.cta}</button><button className="text-link plan-open-link" onClick={() => explore(plan.id)}>Open included features →</button>{plan.id === "TEAM" && <Link className="text-link plan-recruiting-link" href="/recruiting">Hiring? Screen candidates with a real incident →</Link>}</article>; })}</section>
    <section className="feature-breakdown page-pad" id="feature-breakdown"><div className="feature-breakdown-head"><div><h2>Compare plans</h2><p>Checks are included features. Dashes indicate that the feature starts at a higher tier.</p></div><div className="feature-plan-tabs" aria-label="Select dashboard preview">{plans.map(plan => <button className={exploredPlan === plan.id ? "active" : ""} onClick={() => setExploredPlan(plan.id)} aria-pressed={exploredPlan === plan.id} key={plan.id}>{plan.name}</button>)}</div></div><div className="feature-table-scroll"><table className="feature-table"><thead><tr><th scope="col">Capability</th>{plans.map(plan => {const displayed=priceForCadence(plan,billing);return <th scope="col" className={exploredPlan === plan.id ? "selected" : ""} key={plan.id}><button onClick={() => setExploredPlan(plan.id)}>{plan.name}<small>{displayed.price}<span className="sr-only"> {displayed.cadence}</span></small></button></th>;})}</tr></thead><tbody>{featureRows.map((feature, index) => <tr key={feature.label} className={index === 0 || featureRows[index - 1].group !== feature.group ? "group-start" : ""}><th scope="row"><small>{feature.group}</small>{feature.href ? <Link className="feature-label-link" href={feature.href}><b>{feature.label} →</b></Link> : <b>{feature.label}</b>}<span>{feature.detail}</span></th>{plans.map(plan => <td className={exploredPlan === plan.id ? "selected" : ""} key={plan.id}>{typeof feature.included[plan.id] === "string" ? <span className="feature-value">{feature.included[plan.id]}</span> : feature.included[plan.id] ? <span className="feature-check" aria-label={`${feature.label} is included in ${plan.name}`}>✓</span> : <span className="feature-dash" aria-label={`${feature.label} is not included in ${plan.name}`}>—</span>}</td>)}</tr>)}</tbody></table></div>
      <div className="dashboard-preview"><div className="dashboard-preview-copy"><span className="badge badge-blue">SAMPLE DASHBOARD</span><p className="eyebrow">{plans.find(plan => plan.id === exploredPlan)?.name.toUpperCase()} EXPERIENCE</p><h2>{exploredPlan === "FREE" ? "Start with realistic practice." : exploredPlan === "PRO" ? "Turn repetitions into personal readiness." : "Manage a measurable learning program."}</h2><p>This compact preview shows the primary dashboard available at this tier. Preview values are illustrative.</p><button className="button button-blue" onClick={() => choose(exploredPlan)}>Choose {plans.find(plan => plan.id === exploredPlan)?.name} →</button></div><DashboardMock plan={exploredPlan} /></div>
    </section>
    <section className="report-proof page-pad"><header><div><h2>See what the grading report says</h2><p>This is a representative report from the required-field migration incident. The score and feedback come from deterministic repair checks, not an invented AI rating.</p></div><span>Example score <b>86/100</b></span></header><div className="report-proof-grid"><article><h3>Free report</h3><dl><div><dt>Repair</dt><dd>Passed public and hidden validation</dd></div><div><dt>Root cause</dt><dd>The partner-import path omitted a newly required billing region.</dd></div><div><dt>Verification</dt><dd>Migration, serializer, and partner creation checks passed.</dd></div></dl><p><b>Missed evidence</b><br/>The investigation did not inspect the failed partner payload before editing.</p></article><article className="report-proof-pro"><h3>Pro analysis</h3><div className="report-proof-skill"><span>Diagnosis <b>92%</b></span><i><b style={{width:"92%"}}/></i></div><div className="report-proof-skill"><span>Evidence <b>68%</b></span><i><b style={{width:"68%"}}/></i></div><div className="report-proof-skill"><span>Repair <b>96%</b></span><i><b style={{width:"96%"}}/></i></div><div className="report-proof-skill"><span>Verification <b>88%</b></span><i><b style={{width:"88%"}}/></i></div><p><b>Coaching focus</b><br/>Confirm the malformed input at the system boundary before changing the schema path. Your repair was correct; the evidence trail arrived one step late.</p></article></div></section>
    <section className="pricing-explainer page-pad"><div><h2>How plans differ</h2></div><div className="pricing-principles"><article><b>Free practice</b><p>Work through 10 fixed incident templates, the shared daily challenge, public GitHub links, and temporary local uploads.</p></article><article><b>Individual progress</b><p>Pro unlocks 120+ starting scenarios: 10 fixed incidents plus at least one repository-specific challenge from each of 110 curated projects. Repository analysis can surface additional compatible faults.</p></article><article><b>Team readiness</b><p>Team adds unlimited custom incidents, assignments, shared reporting, and an unlimited repository upload allowance for a five-person program.</p></article></div></section>
    <section className="pricing-faq"><div><h2>Questions</h2></div><div><details><summary>Do you need my private repo?</summary><p>No. Starter cases and public repositories work without private repository access.</p></details><details><summary>Is my source ever modified?</summary><p>No. Every rehearsal uses a temporary copy and never writes to the original repository.</p></details><details><summary>What counts toward a rehearsal?</summary><p>A rehearsal begins when its isolated workspace is created and includes one submitted validation report.</p></details><details><summary>Does exploring a paid tier create a charge?</summary><p>No. The plan explorer does not collect a card or begin billing. Paid access begins only after you approve the selected plan at Stripe checkout.</p></details></div></section>
    <section className="closing-cta rr-container"><h2>Your repository stays yours.</h2><p>Temporary copies. Redacted secrets. Allowlisted commands. Expiring workspaces.</p><button className="button button-blue" onClick={() => choose("FREE")}>Start free</button></section>
  </main>;
}
