import Link from "next/link";
import { Suspense } from "react";
import { getAuthenticatedUser, signInPath } from "../auth";
import { getAccountDashboard } from "../../src/accounts/account-service";
import { dailyChallenge } from "../../src/rehearsals/daily";
import { getAssignedTeamWork } from "../../src/team/team-service";

export const dynamic = "force-dynamic";
function metric(value: number | null, suffix = "") { return value === null ? "—" : `${value}${suffix}`; }
function DailyDashboardCallout() { const challenge = dailyChallenge(); return <section className="dashboard-daily"><div><span>Challenge of the Day</span><h2>{challenge.incident.name}</h2><p>Everyone receives the same five-file incident and grading contract today.</p></div><dl><div><dt>Files</dt><dd>{challenge.fileCount}</dd></div><div><dt>Limit</dt><dd>{challenge.timeLimitMinutes}m</dd></div><div><dt>Level</dt><dd>{challenge.difficulty.toLowerCase()}</dd></div></dl><Link className="button" href="/daily">Open challenge →</Link></section>; }

async function DashboardContent() {
  const user = await getAuthenticatedUser();
  if (!user) {
    return <main className="app-page guest-dashboard"><DailyDashboardCallout />
      <section className="guest-dashboard-hero"><div><p className="eyebrow">OPTIONAL ACCOUNT</p><h1>Your incident readiness, over time.</h1><p>Practice stays public. Sign in only when you want each verified result to become part of a personal readiness record.</p><div className="actions"><Link className="button button-accent" href={signInPath("/dashboard")}>Choose a sign-in method →</Link><Link className="button guest-hero-ghost" href="/rehearsals/new">Practice without an account</Link></div></div><div className="guest-score-card"><div><span>READINESS PROFILE</span><b>—</b></div>{["Diagnosis", "Evidence", "Repair", "Verification", "Prevention"].map((skill, index) => <span key={skill}><small>{skill}</small><i><em style={{ width: `${48 + index * 9}%` }} /></i></span>)}<p>Your verified skill signals appear here after sign-in.</p></div></section>
      <div className="guest-path-grid"><article><span>01</span><div><p className="eyebrow">PRACTICE NOW</p><h2>Four complete incident cases</h2><p>Start with database, configuration, provider drift, or webhook replay. No account gate.</p><Link className="text-link" href="/rehearsals/new">Choose a practice case →</Link></div></article><article><span>02</span><div><p className="eyebrow">BRING REAL CODE</p><h2>Analyze a repository safely</h2><p>Paste a public GitHub URL or upload a project. Anonymous snapshots are temporary.</p><Link className="text-link" href="/repositories">Open repository options →</Link></div></article><article><span>03</span><div><p className="eyebrow">SAVE THE PATTERN</p><h2>Build a readiness record</h2><p>Sign in to retain scores, preferences, reports, and filtered repository snapshots.</p><Link className="text-link" href={signInPath("/dashboard")}>Create your account record →</Link></div></article></div>
    </main>;
  }
  const [data, teamAssignments] = await Promise.all([getAccountDashboard(user.email, user.displayName), getAssignedTeamWork(user)]);
  const firstName = user.fullName?.split(" ")[0] ?? user.email.split("@")[0];
  return <main className="app-page"><DailyDashboardCallout />
    <div className="page-title-row"><div><p className="eyebrow">WELCOME BACK, {firstName.toUpperCase()}</p><h1>Incident readiness</h1><p>{data.metrics.completed ? `${data.metrics.completed} completed rehearsal${data.metrics.completed === 1 ? "" : "s"}. Your history is saved to this account.` : "Your readiness profile begins with your first completed rehearsal."}</p></div><Link className="button button-dark" href="/rehearsals/new">Start new rehearsal →</Link></div>
    <section className="grid-4"><div className="stat-card"><small>AVERAGE SCORE</small><strong>{metric(data.metrics.averageScore)}</strong><span className="delta">Completed rehearsals</span></div><div className="stat-card"><small>AVG. DIAGNOSIS</small><strong>{metric(data.metrics.averageDuration, "m")}</strong><span className="delta">Measured after submission</span></div><div className="stat-card"><small>COMPLETION RATE</small><strong>{metric(data.metrics.completionRate, "%")}</strong><span className="delta">{data.rehearsals.length} submitted</span></div><div className="stat-card"><small>SAVED REPOSITORIES</small><strong>{data.repositories.length}</strong><span className="delta">Reusable snapshots</span></div></section>
    {teamAssignments.length > 0 && <section className="member-assignment-feed"><div><h2>Team assignments</h2><p>Work assigned to you by a Team subscription holder.</p></div>{teamAssignments.slice(0, 6).map(item => <article key={item.id}><div><b>{item.repositoryName}</b><span>{item.teamName} · {item.incidentName}</span></div><Link className="text-link" href={item.repositoryId === "challenge-of-the-day" ? "/daily" : "/rehearsals/new"}>Start →</Link></article>)}</section>}
    <div className="dashboard-grid"><section className="panel"><span className="panel-label">REHEARSAL HISTORY</span><h2>Your investigations</h2>{data.rehearsals.length ? data.rehearsals.slice(0, 6).map(session => <div className="session-row" key={session.id}><div><b>{session.incidentName}</b><p>{session.repositoryName} · {new Date(session.completedAt).toLocaleDateString()}</p></div><span>{session.durationMinutes}m</span><strong className="score-ring">{session.score}</strong><span>{session.status === "COMPLETED" ? "✓" : "×"}</span></div>) : <div className="empty-state"><span className="step-icon">01</span><h3>No rehearsals yet</h3><p>Complete an incident and its verified score, duration, and hints will appear here.</p><Link className="button button-blue" href="/rehearsals/new">Choose your first incident →</Link></div>}
      <div className="saved-repositories"><div className="saved-repositories-head"><div><span className="panel-label">SAVED REPOSITORIES</span><h2>Your codebases</h2></div><Link className="text-link" href="/repositories">Add repository →</Link></div>{data.repositories.length ? data.repositories.slice(0, 5).map(repository => <div className="repository-row" key={repository.id}><span className="repo-source-mark compact">{repository.source === "UPLOAD" ? "LOCAL" : "GH"}</span><div><b>{repository.name}</b><p>{repository.displayRef} · {repository.language} · {repository.fileCount.toLocaleString()} files</p></div><span>{new Date(repository.updatedAt).toLocaleDateString()}</span></div>) : <p className="muted-copy">Upload a folder or ZIP, or paste a public GitHub URL. Safe signed-in snapshots can be reused for future rehearsals.</p>}</div>
    </section><aside><section className="panel recommend"><span className="panel-label">RECOMMENDED NEXT</span><h2>{data.metrics.completed ? "Container host mismatch" : "Required field migration"}</h2><span className="badge badge-red">{data.metrics.completed ? "BEGINNER" : "INTERMEDIATE"}</span><p>{data.metrics.completed ? "Practice reasoning across service network boundaries." : "Build an evidence trail through logs, data, migration history, and validation."}</p><Link className="button button-accent" href="/rehearsals/new">Start recommended exercise →</Link></section><section className="panel" style={{ marginTop: 18 }}><span className="panel-label">ACCOUNT DEFAULTS</span><h2>How you rehearse</h2><p><b>Mode</b><br />{data.profile.defaultMode.toLowerCase().replace(/^./, value => value.toUpperCase())}</p><p><b>Time limit</b><br />{data.profile.defaultTimeLimit} minutes</p><Link className="text-link" href="/account">Update account settings →</Link></section></aside></div>
  </main>;
}

export default function Dashboard() { return <Suspense fallback={<main className="app-page"><div className="account-loading"><span className="pulse" /> Loading your readiness profile…</div></main>}><DashboardContent /></Suspense>; }
